### ISSUE TITLE
Filter truncated addresses from backend-service response

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/yoroi-frontend#104]
In the Haskell importer we truncate addresses that are over 2K in size. 
If we plan to make this behavior permanent, we should filter out addresses 2K in size from any backend API request.

We could also choose to filter these from the `backend-service` side instead.

**Comment by nicarq** [comment]
I agree that it could be better to do in the `backend-service` to avoid having ugly patches in Yoroi. I will move this ticket to our backend repo

**Comment by SebastienGllmt** [comment]
Fixed in backend.
