### ISSUE TITLE
Wallet Creation process and buy Trezor link on Wallet add page (4 links)

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#110]
Fixed In:https://github.com/Emurgo/yoroi-frontend/pull/199

**Comment by nicarq** [comment]
Restore: https://youtu.be/PKKWgTNKSks?t=14
Create: https://youtu.be/9jg8lsreIQ8?t=56

**Comment by nicarq** [comment]
How to connect Trezor: https://youtu.be/Dp0wXwtToX0
Referral Link: https://shop.trezor.io/product/trezor-model-t?offer_id=15&aff_id=1281
