### ISSUE TITLE
Update the link once IOHK migrates away from the Cardano-SL repo

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#116]
https://github.com/Emurgo/yoroi-frontend/blob/cd8afff631016b352735fa5a712598b57cf93a88/app/api/ada/adaTypes.js#L7

**Comment by SebastienGllmt** [comment]
I think this is low priority but maybe we should have a way of tracking TODOs in our code instead of opening an issue for all of them individually. 🤔
