### ISSUE TITLE
Can't recover Yoroi Shelley incentivized testnet balances on cardano-wallet

### ISSUE THREAD

**Issue by EdouardLvdl** [Emurgo/yoroi-frontend#1224]
Steps to reproduce:
Have a synced node and import your wallet via $ cardano-wallet following these guides 

https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md

https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool-on-Chain

When using $ cardano-wallet wallet create MyWallet, the wallet is imported but balance is nil, while Yoroi balance check works properly.

**Comment by SebastienGllmt** [comment]
Cardano Wallet doesn't support restoring Byron-era Yoroi wallets. They will add support for this later this week

The Shelley version of Yoroi will ask you to upgrade your Byron-era Yoroi wallet to a "reward wallet" which will be compatible with cardano-wallet (and Daedalus)

**Comment by EdouardLvdl** [comment]
Thanks for your answer. That's probably something that would be useful adding in the current official guides. 

I am a bit disappointed as we were told that both Daedalus and Yoroi would be compatible, and now the incentivized testnet has started without including people who chose the Yoroi path.
