### ISSUE TITLE
Unable to Transfer Funds

### ISSUE THREAD

**Issue by adamparish** [Emurgo/yoroi-frontend#1237]
## About Yoroi
**Network:**  shelley-testnet
**Current version:**  [2.1.2](https://github.com/Emurgo/yoroi-frontend/releases/)
**Commit:**  [19f8a330f8ba7bdc65f039a0a58f53171d40fcfa](https://github.com/Emurgo/yoroi-frontend/commit/19f8a330f8ba7bdc65f039a0a58f53171d40fcfa)

After restoring with my phrase, I get a screen that shows my from my byron addresses to my new shelley address. When I click transfer I get the following error screen.

![Screenshot 2019-12-19 at 1 15 53 AM](https://user-images.githubusercontent.com/272088/71149837-cc860880-21fd-11ea-9021-01bf49122146.png)

**Comment by SebastienGllmt** [comment]
Unfortunately there's nothing we can do about this inside Yoroi 😞
