### ISSUE TITLE
Is ada staking support the mnemonic's length equals 12

### ISSUE THREAD

**Issue by lvshaoping** [Emurgo/yoroi-frontend#1245]
hi ,if mnemonic's length equals 12, is this address support staking ? And about address type = 1 or type =2?

**Comment by SebastienGllmt** [comment]
If you mean a Daedalus 12-word mnemonic, you can get access to the ADA in the account using the "transfer" feature

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/2608559/71435376-14d88580-272c-11ea-9cf7-35a8d3434633.png">

**Comment by lvshaoping** [comment]
> If you mean a Daedalus 12-word mnemonic, you can get access to the ADA in the account using the "transfer" feature
> 
> <img alt="image" width="1169" src="https://user-images.githubusercontent.com/2608559/71435376-14d88580-272c-11ea-9cf7-35a8d3434633.png">

is yoroi will support 12-word mnemonic in future?
