### ISSUE TITLE
Testnet Total Balance does not reflect staking rewards

### ISSUE THREAD

**Issue by baseer** [Emurgo/yoroi-frontend#1248]
I have delegated my ADA and the total balance does not reflect any rewards:

[edit: removed sensitive info]

**Comment by SebastienGllmt** [comment]
This is by design because the "send" screen only takes into account the pre-reward balance (there is a technical reason for why we have to do it that way). It would be confusing to show the total delegated but be unable to actually send part of it.

**Comment by baseer** [comment]
So are you saying that if I somehow stop delegating then the rewards would be received?

**Comment by SebastienGllmt** [comment]
No, you cannot access the rewards in either Daedalus or Yoroi until the end of the testnet

**Comment by avinashcpantawane** [comment]
when testnet will get end or how it will get end

**Comment by SebastienGllmt** [comment]
@avinashcpantawane it will end whenever IOHK releases the Shelley mainnet from my understanding. You can follow IOHK for more information about how transition to the Shelley mainnet will happen once we get closer.
