### ISSUE TITLE
Delegation tab does not work on Firefox Testnet add-on

### ISSUE THREAD

**Issue by TravelingTechGuy** [Emurgo/yoroi-frontend#1276]
**Browser:**
Firefox 71.0 (64-bit)

**Yoroi Version installed:**
Network: shelley-testnet
Current version: 2.2.2
Commit: f9e2d53e9b33246856cb2b0812c2bf07e7d2060c

**Behavior:**
In Delegation (Simple) tab, the scroller keeps scrolling forever, the list of pools never populates, and the search bar doesn't work. 
For comparison's sake, I have the same exact version of the extension installed on Brave (Chrome-like), and the Delegation tab works well.

**Errors observed in Javascript console:**
`[⚠] Request to access cookie or storage on “<URL>[]=0&performance[]=100&source=firefox&mozId=87f1bbd9-ceb2-422c-8db9-85cd3ea881f3&userAda=32419&delegated=%5B%22288888620f1b200ebdff48034d805be8df8bbc70d560fb720863ad1fb957cdda%22%5D&locale=en-US” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. `

```
[❗] The operation is insecure.
kuH4@https://testnet.seiza-website.emurgo.io/_next/static/chunks/commons.f4cc13a1cb372579e979.js:1:918689
i@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:538
obyI/<@https://testnet.seiza-website.emurgo.io/_next/static/chunks/commons.f4cc13a1cb372579e979.js:1:1011970
obyI@https://testnet.seiza-website.emurgo.io/_next/static/chunks/commons.f4cc13a1cb372579e979.js:1:1015394
i@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:538
1TCz@https://testnet.seiza-website.emurgo.io/_next/static/JPqG51d6STPPrYI5fiuZa/pages/_app.js:1:28281
i@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:538
3Ckp/<@https://testnet.seiza-website.emurgo.io/_next/static/JPqG51d6STPPrYI5fiuZa/pages/_app.js:1:36486
value/<@https://testnet.seiza-website.emurgo.io/_next/static/runtime/main-5cb09bdc6e9c1c243c2f.js:1:6421
value@https://testnet.seiza-website.emurgo.io/_next/static/runtime/main-5cb09bdc6e9c1c243c2f.js:1:6596
H@https://testnet.seiza-website.emurgo.io/_next/static/runtime/main-5cb09bdc6e9c1c243c2f.js:1:11243
fLxa@https://testnet.seiza-website.emurgo.io/_next/static/runtime/main-5cb09bdc6e9c1c243c2f.js:1:11295
i@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:538
LwBP@https://testnet.seiza-website.emurgo.io/_next/static/runtime/main-5cb09bdc6e9c1c243c2f.js:1:3488
i@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:538
1@https://testnet.seiza-website.emurgo.io/_next/static/runtime/main-5cb09bdc6e9c1c243c2f.js:1:608
i@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:538
r@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:387
t@https://testnet.seiza-website.emurgo.io/_next/static/runtime/webpack-be30b84510d2aa002225.js:1:250
@https://testnet.seiza-website.emurgo.io/_next/static/chunks/commons.f4cc13a1cb372579e979.js:1:47
commons.f4cc13a1cb372579e979.js:1:1227874
```

**Comment by SebastienGllmt** [comment]
Works for me on multiple machines and I know it's worked for other users. Are you sure you don't have some Firefox setting that is blocking the operation? Notably your error says `content blocking is enabled`. Maybe something like https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookieBlockedForeign ?

**Comment by TravelingTechGuy** [comment]
@SebastienGllmt you hit the nail on the head - it was indeed Firefox's "Enhanced Tracking Protection". 
The article you referenced no longer fits the UI, so here's a short step-by-step (accurate to Jan 2020):

1. Select "Options" from the hamburger menu on the right (gear icon)
2. Select "Privacy & Security" from menu on the left
3. Scroll to "Enhanced Tracking Protection"
4. Select "Custom"
5. Near Cookies, if the dropdown shows "All third-party cookies", change it to "Cross-site and social media trackers"
6. Reopen the Yoroi add-on and  rejoice :)

Now the question remains why does the extension try to use a 3rd party cookie (the domain I managed to locate in the error message is:
`Request to access cookie or storage on “**https://testnet.seiza-website.emurgo.io/**staking-simple/list?sortBy=REVENUE&searchText=&performance[]=0&performance[]=100&source=firefox&mozId=87f1bbd9-ceb2-422c-8db9-85cd3ea881f3&userAda=32419&delegated=%5B%22288888620f1b200ebdff48034d805be8df8bbc70d560fb720863ad1fb957cdda%22%5D&locale=en-US” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.`)

**Comment by SebastienGllmt** [comment]
Seiza is our blockchain explorer which is what keeps track of all the pools in Cardano and information about them. When you want to select a pool to delegate to, we embed Seiza into an iframe and show that in Yoroi. This allows us to have the same staking UI in Seiza, the Yoroi extension and Yoroi mobile so it saves a lot of engineering time. Seiza itself is what is asking for cookies and probably we can disable this when it's embedded inside Yoroi

**Comment by TravelingTechGuy** [comment]
Sounds like the right thing to do. I think going forward, cross-domain cookies will encounter tons of scrutiny and blocking.

**Comment by SebastienGllmt** [comment]
No longer relevant since the ITN is over. Thanks for letting us know about this issue though!
