### ISSUE TITLE
Dashboard shows rewards being auto-delegated?

### ISSUE THREAD

**Issue by ronaldstoner** [Emurgo/yoroi-frontend#1311]
Is Yoroi auto-delegating my rewards? If not, the dashboard view seems a bit misleading as it currently shows "Total ADA" + "Total Rewards" = "Total Delegated". If this is not the intended behavior then the labels should be updated to accurately reflect balances.

**Comment by SebastienGllmt** [comment]
Yes, rewards are automatically delegated as part of the protocol. You can see this for example with the IOHK private pool where the amount of ADA owned by the stake pool increases by the exact amount of ADA they earn every epoch
https://adapools.org/c0cffb1887e57b0b59d3b487e44819c9c8e2de322e2876a5e257d46f7426ee8d

**Comment by ronaldstoner** [comment]
Thank you for the quick reply! I'm glad the protocol and rewards are working this way compared to how other coins and protocols reward delegations.
