### ISSUE TITLE
Reward chart bars can be shorter than the previous epoch

### ISSUE THREAD

**Issue by steffanjj** [Emurgo/yoroi-frontend#1390]
In this example I have 4 epochs with 0 rewards, where the blue bar is shorter then the previous epoch. Should be the same high?
Nice update and release btw, thank you for you hard work.

Version: 2.5.1 - Windows - Chrome

![Capture11](https://user-images.githubusercontent.com/44176456/73818489-cb308f80-47ed-11ea-876c-af9fed846f77.PNG)

**Comment by SebastienGllmt** [comment]
Fixed by #1391
