### ISSUE TITLE
now Yoroi will accept wallet name of at least 1 and at most 40 letters

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#141]
Before:
Wallet name requires at least 3 and at most 40 letters

NOW:
Wallet name requires at least 1 and at most 40 letters

**Comment by sarveshwar-singh** [comment]
https://github.com/Emurgo/yoroi-frontend/pull/84

**Comment by SebastienGllmt** [comment]
I don't know about Cucumber but you can always edit the function the variables get passed to (for example: https://github.com/Emurgo/yoroi-frontend/blob/develop/features/step_definitions/wallet-steps.js#L6
https://github.com/Emurgo/yoroi-frontend/blob/develop/features/step_definitions/settings-ui-steps.js#L18)

**Comment by sarveshwar-singh** [comment]
@SebastienGllmt 
Thanks !!

**Comment by sarveshwar-singh** [comment]
Not able to figure out how to replace `2-characters length` by `0-characters length`

Hence removed the case:
https://github.com/Emurgo/yoroi-frontend/blob/7ef6cf3c47b1116d736709f2822d37374eaa0361/features/wallet-creation.feature#L89

https://github.com/Emurgo/yoroi-frontend/blob/7ef6cf3c47b1116d736709f2822d37374eaa0361/features/settings-ui.feature#L122
