### ISSUE TITLE
Disparity between balance of the rewards account balance and total rewards chart

### ISSUE THREAD

**Issue by mark-stopka** [Emurgo/yoroi-frontend#1415]
Hi,
my Yoroi for Chrome (running in Brave) is showing a disparity between balance of the Rewards account in top right corner and accumulated total rewards in total rewards chart in dashboard, please see screenshot.

<img width="438" alt="yoroi-rewards-error" src="https://user-images.githubusercontent.com/18139116/75520702-748e2e00-5a06-11ea-9aa3-d1642c365d26.png">

Please note that this screenshot is being taken at 07:44 UTC so a long time after the epoch transition, so as my understanding goes, considering I don't even have `jcli` secret key, I was unable to move anything in or out the reward account.

**Comment by SebastienGllmt** [comment]
This is an issue with Jormungadnr, not with Yoroi. The API that returns the reward history is kind of hacky and we make a best-effort to clean it up on our side but unless a more manageable API is provided there is not much we can do.
