### ISSUE TITLE
Transaction history stuck, delegation and total ADA stuck

### ISSUE THREAD

**Issue by IlyaSofronov** [Emurgo/yoroi-frontend#1418]
When I had delegated to another stake pool Transaction history , delegation status and total ADA balance got stuck (endless loading icon).

![Выделение_004](https://user-images.githubusercontent.com/26296741/75623212-714b9b80-5bda-11ea-8c30-c8bdc4284873.png)
![Выделение_002](https://user-images.githubusercontent.com/26296741/75623214-73155f00-5bda-11ea-9f18-30bca17dca35.png)

Epoch 81 must be 1 PERCENT POOL - #2
![Выделение_003](https://user-images.githubusercontent.com/26296741/75623213-727cc880-5bda-11ea-90f8-57fe42233fe4.png)

**Comment by SebastienGllmt** [comment]
Does this still not show anything even after you refresh the page? If so, can you download the logs from the settings page and send them to us?
![image](https://user-images.githubusercontent.com/2608559/75623333-4c602400-5bec-11ea-8f50-75f3629d0e53.png)

**Comment by IlyaSofronov** [comment]
> Does this still not show anything even after you refresh the page? If so, can you download the logs from the settings page and send them to us?
> ![image](https://user-images.githubusercontent.com/2608559/75623333-4c602400-5bec-11ea-8f50-75f3629d0e53.png)

**Comment by IlyaSofronov** [comment]
I downloaded logs, how can I send it to you?
Recieve also is stuck
![Выделение_005](https://user-images.githubusercontent.com/26296741/75623502-1e271800-5bdd-11ea-84f1-b90b1804c434.png)

I have different Total Rewards values on the Summary and on the Chart

**Comment by SebastienGllmt** [comment]
My email is sebastien [at] emurgo . io
We also have a support desk at https://yoroi-wallet.com/#/support

**Comment by IlyaSofronov** [comment]
Done. Sent to yoroi support desk

**Comment by IlyaSofronov** [comment]
After Resync wallet with the blockchain in Yoroi extension it works now, you can close this issue if you think it is ok
