### ISSUE TITLE
Retired stake node appears in Delegation Pool List

### ISSUE THREAD

**Issue by DarkPaladin56** [Emurgo/yoroi-frontend#1441]
Retired stake pool that cannot be found using jcli stake-pools get appears in Delegation's pool list (6c0051b05359460dc2af61bd0f5b4b6c57fd1e9a7b7269f9c717bcafae0fbc55 (BEAVR))

**Comment by SebastienGllmt** [comment]
I'm closing this issue since it's a problem with Tangata-Manu and not with Yoroi. We don't currently have the bandwidth to fix this issue with Tangata Manu unfortunately but we're open to community contributions
