### ISSUE TITLE
Yoroi graph displays wrong amount

### ISSUE THREAD

**Issue by randalert** [Emurgo/yoroi-frontend#1472]
The rewards and total rewards displays the wrong amount. the amount of rewards displayed at the upper right of the dashboard is correct, but the rewards and total rewards is about a thousand ada less. It is ok as long as the amount at the upper right is correct, and it does match what is in Pegasus Tool app, but some of the epoch rewards in the graph are reported as zero or much lower than actual which probably accounts for the difference. Just wanted to let you know.

**Comment by IlyaSofronov** [comment]
@randalert https://github.com/Emurgo/yoroi-frontend/issues/1419
