### ISSUE TITLE
Update ticker did not propagate to yoroi

### ISSUE THREAD

**Issue by zenithpool** [Emurgo/yoroi-frontend#1512]
As a pool operator, I updated the metadata for the pool in the pool registry 4 days ago. The ticker and name show up correctly in daedalus but yoroi still show SUDO and SUDO Stake pool. When can I expect the ticker to be updated?

[PR for changing Ticker](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/2369)

Daedalus showing correct ticker name **ZENITH**
![image](https://user-images.githubusercontent.com/56691430/81622072-aa13a800-93b5-11ea-8fd8-eb0725927e2e.png)

Yoroi Rewards Wallet showing incorrect ticker name **SUDO**
![image](https://user-images.githubusercontent.com/56691430/81622091-b6980080-93b5-11ea-9523-bc6113bd2f5d.png)

**Comment by SebastienGllmt** [comment]
Yes, this was a known issue with the ITN. Since the ITN is shut down, I'm closing this issue
