### ISSUE TITLE
Broken link - "Click here to learn more about using Yoroi with Ledger"

### ISSUE THREAD

**Issue by SL13PNIR** [Emurgo/yoroi-frontend#1528]
![Yoroi link](https://user-images.githubusercontent.com/19766122/82577133-72a9b600-9b82-11ea-890f-6e2a2ab9cc5e.PNG)

Highlighted link address: https://emurgo.io/#/en/blog/how-to-use-ledger-nano-s-with-yoroi-cardano
resolves to homepage (https://emurgo.io/en) instead of linking to blog post. 

Link address should be: https://emurgo.io/en/blog/how-to-use-ledger-nano-s-with-yoroi-cardano.

(Remove hash directory).

Tested in Brave browser.

**Comment by SebastienGllmt** [comment]
Good catch! I fixed it in #1527
