### ISSUE TITLE
Shelly ITN rewards wallet not syncing on Chrome extension and Android wallets

### ISSUE THREAD

**Issue by optictopic** [Emurgo/yoroi-frontend#1530]
I hope this is the correct place to bring this up.  When I try to check my rewards balance on my phone I get the message "We are experiencing synchronization issues..." So I tried the Yoroi ITN Chrome extension and it doesn't work either.  Is this something I can remedy on my end?

**Comment by optictopic** [comment]
Here are the logs from the chrome ext. 
[2020-05-22T10_43_46-06_00-yoroi-shelley-testnet.log](https://github.com/Emurgo/yoroi-frontend/files/4669366/2020-05-22T10_43_46-06_00-yoroi-shelley-testnet.log)

**Comment by SebastienGllmt** [comment]
This is a known issue because the ITN shut down.
