### ISSUE TITLE
My pool not showing in Yoroi, But in Daedalus Wallet : Ticker PEOPL

### ISSUE THREAD

**Issue by narezkumar** [Emurgo/yoroi-frontend#1532]
My pool not showing in Yoroi, But in Daedalus Wallet : Ticker PEOPL

![Screen Shot 2020-05-28 at 8 42 16 PM](https://user-images.githubusercontent.com/5664103/83180465-c177c280-a123-11ea-83e5-162df8ef9ad3.png)

**Comment by SebastienGllmt** [comment]
Closing since the ITN is over anyway
