### ISSUE TITLE
Firefox addon link is not working

### ISSUE THREAD

**Issue by ghost** [Emurgo/yoroi-frontend#1591]
The link for the firefox addon for the mainnet points to https://addons.mozilla.org/en-US/firefox/addon/yoroi/. However, this link leads to a not found page.

The addon for mainnet is instead found on https://addons.mozilla.org/en-US/firefox/addon/yoroi1/ published by some developer who is a user since June 28, 2020. This looks like a fake addon.

**Comment by SebastienGllmt** [comment]
Yes, the one you linked is run by a scammer. Please report their addon and tell the Firefox team this is a fake copy of the real Yoroi.

Whether or not Yoroi is listed on the Firefox addon store is entirely up to the Mozilla team. We're willing to help them with anything they need to list our addon, but it's up to them.

**Comment by ghost** [comment]
I understand. I will report the fake addon. Thanks, @SebastienGllmt.
