### ISSUE TITLE
Ledger nano x withdrawal

### ISSUE THREAD

**Issue by Jokerloz** [Emurgo/yoroi-frontend#1602]
I can't seem to withdraw anything when i go to the last step on it shows up to touch my key and nothing happens to my ldger when i have the ada app open it don't ask me to confirm or deny anything.

**Comment by SebastienGllmt** [comment]
It's a bug with Windows. Don't interact with or close the popup. Instead, you have to ignore the popup and follow the instructions on the webpage and your Ledger device.
