### ISSUE TITLE
TrezorSendStore._sendUsingTrezor fix error logging 

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#163]
put original error in log

**Comment by vantuz-subhuman** [comment]
The question is rather about `TrezorConnect.cardanoSignTransaction` and `trezorResp.payload.error` :)

**Comment by sarveshwar-singh** [comment]
https://github.com/Emurgo/yoroi-frontend/pull/144/commits/5fcedb75c2f9d42332597dce4c0bef8e92b1e6a8

**Comment by sarveshwar-singh** [comment]
@vantuz-subhuman 
Please have a look, if happy please close this issue.

**Comment by vantuz-subhuman** [comment]
Looks perfect!
