### ISSUE TITLE
Is it will support 12-mnemonic

### ISSUE THREAD

**Issue by bulingTang** [Emurgo/yoroi-frontend#1631]
hi , is yoroi will support 12-Mnemonic ?

**Comment by SebastienGllmt** [comment]
Daedalus 12-word mnemonics? Yes, we've supported upgrading from a 12-word Daedalus recovery phrase to a Yoroi-compatible wallet since launch

**Comment by WilsonDoge** [comment]
> Daedalus 12-word mnemonics? Yes, we've supported upgrading from a 12-word Daedalus recovery phrase to a Yoroi-compatible wallet since launch

@SebastienGllmt  We need 12 seed words in Yoroi Chrome. we failed to use Daedalus due its slow connection. please make it hapeen soon

**Comment by SebastienGllmt** [comment]
@WilsonDoge it's already supported. Just create a new Yoroi wallet and then go to the "claim / transfer" page and transfer your funds from your 12-word wallet to your new wallet
