### ISSUE TITLE
Missed era selection with paper wallets

### ISSUE THREAD

**Issue by SL13PNIR** [Emurgo/yoroi-frontend#1647]
The era selection window (below) is missing when attempting to restore a paper wallet. This is preventing the restoration of Shelley wallets created in the ITN.

Byron wallets are restored only.

To replicate:

Add new wallet > Restore wallet > Cardano > Paper Wallet > *Era selection missing*

![image](https://user-images.githubusercontent.com/19766122/89743419-f5b01d80-da9a-11ea-90a8-b7036371bc41.png)

Tested on Brave Browser. Mainnet Yoroi Nightly version 3.1.0 (Commit: d7ed82af3e37f4215d997625f3ff3d59417d841d)

**Comment by SebastienGllmt** [comment]
I don't think we allowed paper wallets during the ITN

**Comment by SL13PNIR** [comment]
Paper wallets were included in the November 29th snapshot for the ITN:

![Wallet types for ITN November 29th snapshot](https://user-images.githubusercontent.com/19766122/89770112-2f624200-daf6-11ea-8c7a-fdef1e337842.png)

I've discussed this problem with you on the ambassador slack.

There's also many others with have paper wallets used in the ITN, you replied to one such here on the Cardano Forum: https://forum.cardano.org/t/yoroi-paper-wallet-view-reward/35232/11

**Comment by SebastienGllmt** [comment]
Claiming ITN rewards from a recovery phrase is a different subject than wallet recovery. You can expect paper wallets to show up on the "claim" page in a later release (hopefully this week)

**Comment by SL13PNIR** [comment]
Ok I appreciate that and I'm honestly thankful for the work you're doing, but please understand how I got here in the first place from our prior conversation where you said I'd be able to view my rewards:

![image](https://user-images.githubusercontent.com/19766122/89802231-23dc3e80-db29-11ea-8f6e-e2b8c7651e02.png)

**Comment by qualle16** [comment]
Yep.....still in the land of the forgotten. Although papers were propagated big time back then....
Please add the 21 yoroi ITN Redemption ASAP.

**Comment by SebastienGllmt** [comment]
Closing since this feature is implemented in #1653
