### ISSUE TITLE
Pool Listing produces Errors

### ISSUE THREAD

**Issue by leo42** [Emurgo/yoroi-frontend#1651]
When looking up my staking pool with the ID : 89eba2781e5cd11ccda6be56503702a39e9941e522f04cd5bba22957 

An error shows up and no information about the pool is displayed

![image](https://user-images.githubusercontent.com/4371293/89900332-497e4c00-dbec-11ea-8c9b-1316c074c5a0.png)

**Comment by SebastienGllmt** [comment]
This is a server issue due to high load. It's not specific to the pool info endpoint. We've upgraded our server so try and handle the extra load.

**Comment by SebastienGllmt** [comment]
After some more investigation, I think this is an issue with SMASH. IOHK is updating SMASH this week to fix some issues, so it may fix this one. I'll keep the issue opened until then

**Comment by SebastienGllmt** [comment]
After some investigation, it turns out this was the error

https://github.com/Emurgo/yoroi-graphql-migration-backend/pull/30

**Comment by leo42** [comment]
Because i used a SRV relay record.....

Thank you so much :)

**Comment by SebastienGllmt** [comment]
Closing since it's been fixed
