### ISSUE TITLE
Question: Is the javascript for creating, signing, posting transactions in its own reusable library?

### ISSUE THREAD

**Issue by ozyman42** [Emurgo/yoroi-frontend#1654]
I would like to be able to create, sign, post transactions and staking certificates, etc. directly from the browser using javascript.
I noticed that [input-output-hk/cardano-js-sdk](https://github.com/input-output-hk/cardano-js-sdk) isn't being actively maintained, and [input-output-hk/cardano-launcher](https://github.com/input-output-hk/cardano-launcher) (used by Daedalus) requires Node.js, so this can't be used for a browser-only solution.

**Comment by SebastienGllmt** [comment]
This is what you're looking for https://github.com/Emurgo/cardano-serialization-lib
