### ISSUE TITLE
Epoch Progress panel shows incorrect Day count in Time until Epoch end

### ISSUE THREAD

**Issue by khenzar** [Emurgo/yoroi-frontend#1659]
Yoroi Extension - Dashboard - Epoch Progress card - "Time until Epoch end:"

The timespan information has incorrect number shown in Day field. The value displayed is incorrectly inreased by +1 day.

One epoch is 5 days, so the timespan until epoch end must be less than 5 days.
For example, if 22 hours passed since the start of an epoch, than timespan until the epoch ends is 4 days 2 hours.
Instead, Yoroi extension displays 5 days 2 hours.
On the last day of an epoch, the time should show "0 days X hours X minues...".

Screenshot for proof:
![image](https://user-images.githubusercontent.com/2130285/90680150-abc8f380-e261-11ea-9af3-2504aff8326f.png)

**Comment by khenzar** [comment]
I just found this commit by @SebastienGllmt : [https://github.com/Emurgo/yoroi-frontend/commit/4616c08d8b176da79b086a2cb6eeb408d9beddf6](url)
Not sure if that fixes the issue but seems related.

**Comment by SebastienGllmt** [comment]
Yes, it's already fixed on Yoroi Nightly, but thanks for reporting!
