### ISSUE TITLE
'Delegation List' tab: margin % display wrong and pledge header wrong  

### ISSUE THREAD

**Issue by bidfish** [Emurgo/yoroi-frontend#1671]
In Yoroi 3.3.0 'Delegation List' tab:

- Percent pool costs are 100x too big 
- right tab: 'Cost' header should read 'Pledge'

Example:
**[ATADA] ATADA Stakepool Austria**

Pool Size________Costs___________Costs            
0.5%___________(227.33% + 340)___2.50M
166.88M ₳

Margin percentage is 2% instead of 227.33%
Right column header should read 'Pledge'

**Comment by SebastienGllmt** [comment]
This is a known issue for small display sizes. We're deploying the fix soon. Thanks for reporting though!

**Comment by bidfish** [comment]
Thx. After decreasing display size in Chrome from 125% to 100% display is OK
