### ISSUE TITLE
Add a timestamp for the nearest reward

### ISSUE THREAD

**Issue by IlyaSofronov** [Emurgo/yoroi-frontend#1728]
We have timestamps for the upcoming rewards and countdown for the nearest reward day. 
It's ok but when you try to calculate the reward day in your head you can easily make a mistake for a +- 1 day.
Below I made a suggestion of how we can add a timestamp for the nearest reward day.
![Выделение_001](https://user-images.githubusercontent.com/26296741/93732218-947f7c00-fbfa-11ea-8af3-ccbfcf03bc2f.png)

**Comment by nicarq** [comment]
@IlyaSofronov good idea. makes sense!

**Comment by nicarq** [comment]
@Marta-Ryzhok 🙏

**Comment by Marta-Ryzhok** [comment]
@nico-bianco @IlyaSofronov 
yeah, agree on that the nearest reward day should be mentioned.

What if we show the current Epoch in the section "Upcoming rewards"? This way will be displayed two upcoming epochs instead of three. But this makes more sense to me

![image](https://user-images.githubusercontent.com/45553506/94676545-2e92a300-0324-11eb-9179-fe1e3f236c88.png)

**Comment by IlyaSofronov** [comment]
@Marta-Ryzhok This idea looks good to me. One thing I would like to see three upcoming epochs not two, it gives more predictability :)

**Comment by Marta-Ryzhok** [comment]
@nicarq @IlyaSofronov 
proposed changes:
- highlighted the "withdraw rewards" button
- added names of stake pools next to the icon
- removed grey squares below the time of upcoming epochs, it fits for the active countdown timer


![image](https://user-images.githubusercontent.com/45553506/95300919-90a15a00-0888-11eb-9640-a39235bb1d2d.png)

**Comment by IlyaSofronov** [comment]
@Marta-Ryzhok I really like your proposals! Maybe it would be cleaner to make "**Time of the nearest reward**" shorter? Just put "**The nearest reward**" instead

**Comment by Marta-Ryzhok** [comment]
@IlyaSofronov 
yeah agree. Ah, and also there is no need to show those extra arrows when only one page for a now is displayed
![image](https://user-images.githubusercontent.com/45553506/95320992-061a2400-08a3-11eb-8e26-ed18dfa1df58.png)


![image](https://user-images.githubusercontent.com/45553506/95320923-ea168280-08a2-11eb-8eaa-26aec734f4dc.png)

**Comment by IlyaSofronov** [comment]
Done
