### ISSUE TITLE
nightly release shows mainnet banner while using a testnet wallet

### ISSUE THREAD

**Issue by rcmorano** [Emurgo/yoroi-frontend#1732]
It correctly displays amounts in `tADA`, but the `YOU ARE YOROI NIGHTLY` banner always shows `MAINNET` as network to me:

![image](https://user-images.githubusercontent.com/55876/94374243-2ad80400-010b-11eb-95e9-01056f296559.png)

**Comment by nicarq** [comment]
Thanks Roberto!
