### ISSUE TITLE
Cannot claim staking rewards

### ISSUE THREAD

**Issue by 0xmichalis** [Emurgo/yoroi-frontend#1762]
I am getting the following error in Brave using the Yoroi extension (v3.7.3):
![Screenshot from 2020-10-08 20-01-14](https://user-images.githubusercontent.com/3900799/95496480-32b46580-09a1-11eb-9611-881ba03dd936.png)

When inspecting the response in the Network tab, I see the following:
Request:
```
POST https://iohk-mainnet.yoroiwallet.com/api/txs/signed
```
Response:
```
{"error":{"response":"Cannot read property 'data' of undefined"}}
```
The request payload sent by the extension includes my `signedTx`.

**Comment by 0xmichalis** [comment]
After a bunch of retries, my transaction went through. I am going to leave this issue open until someone verifies the issue has been properly fixed (looked like a backend issue).

**Comment by v-almonacid** [comment]
@kargakis yes this was a backend issue. Will pass the info to our devops. Thanks for the heads up!
