### ISSUE TITLE
Unable to add Trezor Model T wallet protected with passphrase

### ISSUE THREAD

**Issue by mark-stopka** [Emurgo/yoroi-frontend#1764]
I am unable to add Trezor Model T wallet protected with passphrase, when I follow the process, Trezor `connect` website won't prompt me for passphrase...

I see following error after clicking **Pair devices**...

![image](https://user-images.githubusercontent.com/18139116/96374977-6a2bca80-1176-11eb-801f-e60ea765993d.png)

This may be resolved after merging https://github.com/Emurgo/yoroi-frontend/pull/1752 `trezor-connect` library update...

**Comment by mark-stopka** [comment]
Issue just replicated on a 2nd Windows 10 laptop, fresh install of Yoroi, I have also removed and installed back the extension, same issue...

**Comment by mark-stopka** [comment]
I was able to confirm today that my Mac OS X set-up wallet is still able to make transactions and prompts for passphrase when required...

**Comment by mark-stopka** [comment]
New https://github.com/Emurgo/yoroi-frontend/pull/1765 was merged, hopefully this will be fixed with new Yoroi version, @mmahut, have you tested some nightly build?

**Comment by mmahut** [comment]
This is working now.
