### ISSUE TITLE
Total rewards stuck

### ISSUE THREAD

**Issue by IlyaSofronov** [Emurgo/yoroi-frontend#1780]
Total rewards have not increased in recent eras although they have not been withdrawn
 Version 3.8.3
![Выделение_002](https://user-images.githubusercontent.com/26296741/97749299-66f2f000-1b21-11eb-9569-118b81cce343.png)

**Comment by nicarq** [comment]
@IlyaSofronov thanks for the ticket! 

There is indeed a bug for epoch 225. We are debugging right now. For Epoch 226, we probably should hide it, because it's the epoch that hasn't ended yet, so there is no rewards distribution yet
