### ISSUE TITLE
Transaction memo

### ISSUE THREAD

**Issue by vantuz-subhuman** [Emurgo/yoroi-frontend#179]
## Abstract
We want for user to be able to attach private memos to sent transaction, and then later see them in the transaction history. Memos are private, so no one else should be able to access them. When the same wallet is restore on another device - memos should be visible too.

### New UI
When user opens "Send" tab - under the existing fields for address and amount there should be new small element, like a button or a link, saying "Add memo >". When user clicks it - a text area field opens under it. Something like this (general idea):

![image](https://user-images.githubusercontent.com/5585355/50155690-cc4ae880-02dd-11e9-8326-c072cd87e071.png)

![image](https://user-images.githubusercontent.com/5585355/50155779-09af7600-02de-11e9-86e1-901b94da75f7.png)

When text area is opened, user prolly should be able to click on "Add memo" again and it will hide. If text area is not empty in that moment - it should ask something like "Remove memo? Yes/Cancel", and if clicked "Yes" - text area closes and text is cleared, and if clicked "Cancel" - nothing happens.

When user clicks "Send" on the tx - if tx itself is validated successfully and sent out - Yoroi checks if there's any text in the memo field, and if there is - encrypts this memo and sends to the storage.

### Storage
We want to make memos as private as the wallet itself, meaning that even we shouldn't have access to it and be responsible for its preservation, so we can't send info to our server. Therefore for memo-storage we shall use some external service where user controls everything by themselves.

Later we might support multiple different storage options, but for now we need to create a main reference integration with probably Dropbox (maybe something else if rationalised).

So Yoroi app (client-side) also needs to manage a sync with a remote 3rd party file-storage.

### User/Storage (auth)
For us to be able to use the external storage - user must have an account on that service and also must authorise Yoroi as a valid API caller.

There must be a new section in the settings menu, something like "Linked accounts", where "Dropbox" will be only one of the options. Something like this:

![image](https://user-images.githubusercontent.com/5585355/50157711-387c1b00-02e3-11e9-8a0d-6d8b08b2ffe8.png)

When user sends a transaction and clicks "Add memo" - Yoroi should check if auth with Dropbox is established. If not - a message like "In order to attach private memos to transaction you need to link a Dropbox account." with buttons like: "Link Dropbox" (clicks and goes to the settings page probably), and "Nah" (does nothing and cancels memo field appearance).

### Storing/Retrieval 
Memos should be globally synced among the same wallets, which means that if user restores the same wallet on another device - they should be able to see the same memos for the same transactions.

So Yoroi should store each memo under the transaction ID, and also for each new (non-local) transaction - check if there's a memo for this transaction ID in the storage.

When Yoroi is just started and a wallet is restored - history of transactions is restored, and Yoroi should also check for all transactions if there are memos for them.

Optionally, it might only check for memos when transactions are actually expanded in the UI.

### Privacy
All memos are strictly user-private for now, so there should be some information about it in the UI, prolly a comment under the memo text area on the "Send" tab.

### Encryption
Before sending memos to the storage Yoroi should encrypt them using something like a hash of the wallet **private** key, so if user has multiple wallets - memos from different wallets are not mutually-readable.

When wallet checks for an existing memo and downloads it - it should try decrypt it using the same key hash. If decryption failed - means something is wrong (like someone messed up with the storage manually) and error should be logged and reported.

**Comment by nicarq** [comment]
it’s really good! instead of a hash of the master private key, I would use a hash of the master public key. This way it’s also compatible with hardware wallets.

**Comment by vantuz-subhuman** [comment]
> instead of a hash of the master private key, I would use a hash of the master public key. This way it’s also compatible with hardware wallets.

Makes sense if we consider root public key as secret as the private key 🤔 But yeah, for hardware wallets I guess there's no much alternatives

**Comment by SebastienGllmt** [comment]
See #234 for another spec for this

**Comment by SebastienGllmt** [comment]
I'm going to close this since this is now strictly replaced by #234
