### ISSUE TITLE
Correct Horse Battery Staple

### ISSUE THREAD

**Issue by vantuz-subhuman** [Emurgo/yoroi-frontend#180]
## Abstract

![image](https://user-images.githubusercontent.com/5585355/50168506-a84acf80-02fc-11e9-8cc8-6372d968f9a7.png)

## Details

Remove all pointless requirements from the password, except some decent minimal length.

**Comment by SebastienGllmt** [comment]
I agree. This is a simple change to `validators.js` I believe. I also think we should take out the minimum 3-letter limit for wallet names. Why is a 2-letter wallet name invalid?
We could also add a rating for how "good" your password is (I'm sure there is a library that does this) but these rating systems are usually garbage anyway so maybe not worth it.

**Comment by vantuz-subhuman** [comment]
Related: https://github.com/input-output-hk/daedalus/issues/619

**Comment by vantuz-subhuman** [comment]
Also related: https://www.baekdal.com/trends/password-security-usability

![image](https://user-images.githubusercontent.com/5585355/50407550-e8bdb800-07ea-11e9-86da-a545f33a6c9d.png)

**Comment by sarveshwar-singh** [comment]
@SebastienGllmt 
>Why is a 2-letter wallet name invalid?

https://github.com/Emurgo/yoroi-frontend/pull/192
It's already changed to 1 letter.
