### ISSUE TITLE
Ledger Nano S connectivity issue

### ISSUE THREAD

**Issue by Antares456** [Emurgo/yoroi-frontend#1862]
Hi,
could you please advise on the following:

When I am trying to sign transaction using my Ledger Nano S I get directed by Yoroi to open Cardano app on Ledger Nano S which I do. After that normally comes the step of exporting my public key... But not recently. Yoroi gets me message which reads:

"Something unexpected happened. Please retry."

I have the latest firmware and the latest version of the Cardano app in the Ledger. I updated the app today. The same browser, operating system,... as the last time I was normally sending ADA.
I have the same problem with Daedalus wallet. AdaLite worked just fine.

Cheers everyone.

**Comment by VenerableChris** [comment]
Seconded. I also had to use Adalite to make any transactions.

**Comment by rdlrt** [comment]
Should be fixed with update 3.8.5 that Seb pushed an hour ago

**Comment by SebastienGllmt** [comment]
Should be fixed if you update to the latest version of Yoroi

**Comment by Antares456** [comment]
Thank you for notifying.

Cheers.
