### ISSUE TITLE
Transaction history in a non-(directly)-involved wallet

### ISSUE THREAD

**Issue by psychomb** [Emurgo/yoroi-frontend#1918]
Hi Team, 

Some weird behaviour (or at least unexpected) from my side.

I use a Trezor HW as a reward account for one pool (STKH1). 

I have registered a second pool (STKH2), funded the pledge for this second pool by sending some ADA from the pledge account of the first pool.

I was surprised to see a 0 ADA transaction appearing in my STKH1_reward history (image below), where the sender is STKH1_pledge, the receivers STKH1_pledge (the change for the tx) and STKH2_pledge.

![IMAGE 2021-02-03 17:33:15](https://user-images.githubusercontent.com/46930715/106778095-e672ec80-6645-11eb-9e95-88bb49b6f4b9.jpg)

It is worth noting that STKH1 and STKH2 share the same reward account (Trezor HW). But it was a bit surprising to see this transaction appears in its history. This wallet never signed anything, as reward accounts don't have to. It was however mentioned as a reward account in the STKH2 pool registration.

Is this behaviour expected ?

**Comment by SebastienGllmt** [comment]
Yes, this is expected and by design since this transaction is related to your wallet through the content of the certificate.

**Comment by psychomb** [comment]
👌thanks @SebastienGllmt
