### ISSUE TITLE
Ergo - not showing transactions for a receiving address

### ISSUE THREAD

**Issue by bbhart** [Emurgo/yoroi-frontend#1923]
This is for Ergo network.

I created a new receiving address in Yoroi (9gU1sgKMS45hZ6G5rrxHqDKr8KtmaaAhTirh72YEUsoKxfH2UJM) and use that for nanopool mining. According to nanopool and the ergo blockchain explorer, [there have been two transactions to my receiving address](https://explorer.ergoplatform.com/en/addresses/9gU1sgKMS45hZ6G5rrxHqDKr8KtmaaAhTirh72YEUsoKxfH2UJM), one for ~9.63 and another for ~45.38. 

1 - Confirmation that I own the receiving address.
![yoroi1](https://user-images.githubusercontent.com/474498/107883797-15e3ed80-6ebf-11eb-8790-d1ad6a67f828.jpg)

2 - Transactions not shown in the list.
![yoroi2](https://user-images.githubusercontent.com/474498/107883808-2bf1ae00-6ebf-11eb-9623-5ffc13cfc97f.jpg)

3 - Confirmation that Yoroi believes it is up-to-date (Last sync: a few seconds ago)
![yoroi3](https://user-images.githubusercontent.com/474498/107883823-3e6be780-6ebf-11eb-8f15-304075307efd.jpg)

I've done a 'Resync wallet with the blockchain', with no effect.

**Comment by SebastienGllmt** [comment]
There is an issue with our node's sync. We're aware of the issue

**Comment by bbhart** [comment]
Thanks @SebastienGllmt, I'll check back later and close this when I confirm, then. Do you think it's possible to somehow notify the user when the node is out of sync? If so I'll open a feature request. This one _really_ had me questioning whether I knew how some of this stuff worked.

**Comment by bbhart** [comment]
I'm now able to see the new transactions. Closing...
