### ISSUE TITLE
Reward missing (Chart bug)

### ISSUE THREAD

**Issue by mcpape** [Emurgo/yoroi-frontend#1939]
> I have the same issue for epoch 247 which happens to be the epoch in which I switched from one pool to another.

_Originally posted by @ShimShamSam in https://github.com/Emurgo/yoroi-frontend/issues/1932#issuecomment-782719546_

I have the same issue and it is still present for epoch 247. I switched the pool for this epoch.

**Comment by mmahut** [comment]
Are you still seeing this issue? If so, can you please post your stake address to the yoroi support?

**Comment by mcpape** [comment]
Yes, I am still seeing this issue.

I am not an expert and have a question about the staking address. So maybe apologize the question.
If I post the stake address to the support and have to add the E-Mail for opening a ticket, isn't there a loss of anonymity? One can immediately see my total own ADA. Please correct me, if this is wrong or there is another solution!

**Comment by mcpape** [comment]
This morning the chart is showing correctly.
