### ISSUE TITLE
People who registered using Yoroi for Project Catalyst see no voting power

### ISSUE THREAD

**Issue by mark-stopka** [Emurgo/yoroi-frontend#1974]
I have registered using Yoroi Chrome for Project Catalyst, and have no voting power although the wallet was properly funded during the snapshot. Same issue has been confirmed by several other users on both Twitter and Discord.

**Comment by AskBid** [comment]
I can confirm to experience the same issue with Yoroi Chrome.
I moved the funds from a normal wallet back to HW after the snapshot, but no voting power shows up in the CatalystVoting App.

**Comment by mark-stopka** [comment]
> I can confirm to experience the same issue with Yoroi Chrome.
> I moved the funds from a normal wallet back to HW after the snapshot, but no voting power shows up in the CatalystVoting App.

Same, the wallet had ~ 7k ADA at time of registration ( 19th of February), then about 3 hours before snapshot I transfered other funds and went to sleep, in the morning I transfered them back where they belong.

**Comment by mark-stopka** [comment]
Not sure if this applies to Yoroi users, but statement from IOG... so there is hope...

![image](https://user-images.githubusercontent.com/18139116/110176537-c16bc800-7e03-11eb-8861-09ba311f3a1e.png)


EDIT: This seems to be a different issue.

**Comment by mark-stopka** [comment]
Official statement:

![image](https://user-images.githubusercontent.com/18139116/110182515-3394da80-7e0d-11eb-8570-e3c6284ea192.png)

**Comment by nickolanaous** [comment]
I also have 0 voting power but have registered using Daedalus. The issue may not only be limited to Yoroi.

**Comment by SebastienGllmt** [comment]
Hey folks, it looks like CIP15 (https://github.com/cardano-foundation/CIPs/blob/master/CIP-0015/CIP-0015.md) is incorrect. I will write up a modification to CIP15 based on feedback from IOHK on this topic and we'll have more public message on the next steps as well

**Comment by Zenleaf** [comment]
Same here

**Comment by trjones8918** [comment]
Thanks for the info @SebastienGllmt . We will be sure to spread the word once you guys release an official statement.

**Comment by kafcha** [comment]
+1

**Comment by mark-stopka** [comment]
Update; TL;DR:

Yoroi users will be able to vote from 19:00 UTC 26 March to 19:00 UTC on 29 March.

> Dear Project Catalyst members,
> 
> On Friday evening, we started the voting process for Fund3. 
> 
> The vast majority of Daedalus holders experienced no issues. Unfortunately, 1,800 Yoroi users have so far been unable to cast their votes due to an integration issue affecting their voting power.
> 
> We have now completed our technical investigation and good news… we have identified the issue and fixed it. All eligible Yoroi users will get to vote this round.
> 
> Unfortunately, however, we cannot reopen voting to Yoroi right now without disrupting the current voting. Instead, we shall open up a special voting round for all Yoroi users at the end of this month, from 19:00 UTC 26 March to 19:00 UTC on 29 March. 
> 
> We’re keeping the process super simple. You won’t need to download anything and we’ll reuse the existing snapshot from Friday, so you won’t need to move your funds again if you were using a hardware wallet or holding your ada funds on an exchange.
> 
> Yoroi users will simply need to open up the app again after 19:00 UTC 26 March, and complete the voting by rescanning. You WILL need your QR code and PIN to do so. 
> 
> Please ensure you keep your voting QR code & PIN safe and secure until then. Remember, if you do not have this, you will not be able to vote.
> 
> It does mean Yoroi users will have to wait before voting. But we hope in the meantime you will explore the proposals in the app. 
> 
> We are very sorry about the inconvenience caused by this issue and that you will have to wait till the end of the month to cast your vote. As soon as that has happened, we’ll tally the votes together and announce the results.
> 
> We appreciate that this is not a perfect solution. Doing it this way also means we won’t need to delay the timings for fund awards  - we felt it was very important to stick to the plan here.
> 
> Despite this issue, Project Catalyst continues to go from strength to strength. We now have:
> 
> 15k + people registered on Ideascale
> 20k ADA holders have already registered to vote in Fund3 
> 72k votes cast so far
> Thanks again for being a part of the experiment. Not everything always goes perfectly - your ongoing support is much appreciated.
