### ISSUE TITLE
Yoroi Chrome - visual bug when clicking "my wallets"

### ISSUE THREAD

**Issue by AlexDochioiu** [Emurgo/yoroi-frontend#1990]
Versions:
Brave Browser: Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)
Yoroi: 4.1.2

Steps to reproduce:
1. Open Yoroi Extension in Brave Browser
2. Select any wallet
3. Click on "My Wallets" button from the left sidebar

Outcome:
-- Full (empty) white page appears

Note: To get back, I either have to close and open again the extension, or click the "back" button from the browser.

**Comment by SebastienGllmt** [comment]
Thanks for the bug report! We've already fixed this issue and it will be part of the next release 👍
