### ISSUE TITLE
Utxo selection sub optimal

### ISSUE THREAD

**Issue by MarcelKlammer** [Emurgo/yoroi-frontend#1996]
I just sent 50 ADA intra wallet.

I had plenty of utxos with more than 50 ADA on them, but the coin selection chose to select all of my token holding utxos (three different tokes with 2, 2 and 1.444 ADA values). So the tokens might now be consolidated, but the transaction cost more transaction fees.

Is that intentional behavior?

**Comment by SebastienGllmt** [comment]
The UTXO selection is roughly in order of when the utxo entries were created. 
IOHK has done some research on the implications of different input selection algorithms and the result is that some things that seem like they make more sense (like picking a UTXO entry with more than 50 ADA in it in your case) can actually lead to poor performance down the road (blog link: https://iohk.io/en/blog/posts/2018/07/03/self-organisation-in-coin-selection/ )

IOHK has a CIP that describes a better input selection that we use, but it's significantly more complicates so we've never prioritized implementing it.

**Comment by MarcelKlammer** [comment]
Thanks for the info, Sebastien.
