### ISSUE TITLE
`ergo_request_read_access().then()` silently fails in Example dApp

### ISSUE THREAD

**Issue by flexabyte** [Emurgo/yoroi-frontend#2013]
I've been playing around with the Ergo Wallet Dapp Connector trying to see how to integrate it into my app. I don't believe this to necessarily be an issue with the code, but there may be a lack of error handling in the extension.

## The Problem I'm Having
Requesting access to the Ergo wallet via `ergo_request_read_access` executes and does nothing in `yoroi-frontend/packages/yoroi-ergo-connector/example/index.js`. 

## Steps to Reproduce
1. Build extension from source:

```
npm run prod:stable
```

2. Install extension into browser with 'Load Unpacked' and selecting `build` directory.
3. Build Dapp Connector from source:

```
npm run prod:stable -- --yoroiExtensionId=<id_from_installed_yoroi_extension>
```
4. Edit `example/index.js` to add line after `request_read_access` promise executes:

```
function initDapp() {                                                                                              
    ergo_request_read_access().then(function(access_granted) {
        alert("Request Read Access Promise Executed...");                                      
        if (!access_granted) { 
```

5. Run Demo App:

```
npm install && npm run start
```

## Expected Behaviour
Status should update to "Wallet successfully connected", instead it remains at "Wallet not connected."

I have also tried using the Yoroi Extension from the Chrome Store, replacing the ID with that when building the Dapp connector and still get the same result. I also added the following line in after the `then(function(access_granted) {` block:

```
.catch((wallet_error) => console.log(wallet_err));
```

But it appears no error is thrown. I'm not sure what's going on here, but either way it seems like unexpected behaviour either from the dApp Connector or the example dApp. Thanks.

**Comment by SebastienGllmt** [comment]
`npm run prod:stable`
you need to specify the connector ID from the Yoroi Extension
The reason it fails silently is because the error is appearing in the background page logs (you can access the background page from the chrome://extensions page under the details > background)

**Comment by flexabyte** [comment]
Thanks for the response Sebastien,

I'm away from my laptop right now but just to be clear, you need to specify the ID of the connector extension when building the yoroi-extension? So you pass the extension ID to the connector and vice versa? That would make sense, but just wanted to clarify, I'll update when I've tested this!

**Comment by flexabyte** [comment]
So it took some digging to find the exact build argument, but now when I build Yoroi with:

```
npm run prod:stable -- --ergoConnectorExtensionId=kfbllllphljcokpnlffianlnlickakef
```

Build the ergo-dapp-connector with:

```
npm run prod:stable -- --yoroiExtensionId=padckojnibpgknddlhcpebdfkaiepkkp
```

and run `npm run start` in the example app, I reload the extensions in the browser and it doesn't silently fail anymore. There is still the following errors:

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```
```
Uncaught (in promise) TypeError: Cannot read property 'postMessage' of null
    at inject.js:260
```

Since my error pertains to something beyond the scope of this initial issue I'm happy to close this and hopefully discuss with someone on the Discord who has been able to get the Ergo connector running. Thanks!
