### ISSUE TITLE
[AddWalletPage] HelpLinkFooter disappear when screen under 914px

### ISSUE THREAD

**Issue by nicarq** [Emurgo/yoroi-frontend#205]
<img width="917" alt="screen shot 2018-12-30 at 12 47 43 pm" src="https://user-images.githubusercontent.com/1622112/50546961-414ce500-0c31-11e9-96d9-a7f45d02c369.png">

**Comment by sarveshwar-singh** [comment]
plus:
![image](https://user-images.githubusercontent.com/19986226/51675490-29d9ff80-2017-11e9-9f1d-650e45d519dd.png)

**Comment by SebastienGllmt** [comment]
I would guess this is because of the upgrade to `react-router`

https://github.com/Emurgo/yoroi-frontend/pull/197/files

You can see I added the `height: '100%'` at two different places to make the UI work and this probably also got rid of the scrollbar.
