### ISSUE TITLE
Unexpected error with Ledger Nano X

### ISSUE THREAD

**Issue by scarolan** [Emurgo/yoroi-frontend#2083]
The delegation process is confusing and probably a bit scary for new users.

The dialog box that pops up multiple times says to "Touch your security key".

I got all the way to the delegate pool screen and the process failed with an "Unexpected error".

**Comment by scarolan** [comment]
I'm trying to reproduce the error again so I can post screenshots or more detail, but it's stuck on "Touch your security key" and won't go any further now.

**Comment by v-almonacid** [comment]
@scarolan is your firmware and ADA app on your ledger up-to-date? Current version should be  `2.2.0`
