### ISSUE TITLE
How can I connect to a test network?

### ISSUE THREAD

**Issue by danielmain** [Emurgo/yoroi-frontend#2085]
Hello is there a way to create a wallet in a test network? Similar like Metamask
That would allow me to test my dApp using fake ADAs.

![image](https://user-images.githubusercontent.com/4303099/117336711-ccdb7e00-ae9c-11eb-82f8-39583c6a721c.png)

thank you

**Comment by v-almonacid** [comment]
You can do this by building the app using the dev configuration: `npm run dev:stable`. With this option you can choose to create/restore wallets on the public testnet.

Instructions for doing this are included in the README.
