### ISSUE TITLE
API and DApps integration

### ISSUE THREAD

**Issue by dmitrystas** [Emurgo/yoroi-frontend#2155]
Hi, Yoroi Team.

Is there any plans for API support and 3rd party Dapps integration, like MetaMask has

> The extension injects the Ethereum web3 API into every website's javascript context, so that dapps can read from the blockchain.
> 
> MetaMask also lets the user create and manage their own identities (via private keys, local client wallet and hardware wallets like Trezor™), so when a Dapp wants to perform a transaction and write to the blockchain, the user gets a secure interface to review the transaction, before approving or rejecting it.

?

**Comment by rooooooooob** [comment]
For Ergo we already have it implemented in the nightly releases using the [EIP-0012 spec](https://github.com/ergoplatform/eips/pull/23). For Cardano it is not implemented yet but we have already drafted a CIP for the spec which can be found [here](https://github.com/cardano-foundation/CIPs/pull/88). It is still awaiting feedback as we want to have a wallet-agnostic API in the best interests of the entire Cardano community, rather than multiple proprietary/wallet-specific APIs, which would hurt dApp developers in the long-term.

**Comment by zuzunker** [comment]
The implementation for the Cardano connector has already started, you can look out for PRs like https://github.com/Emurgo/yoroi-frontend/pull/2213 and https://github.com/Emurgo/yoroi-frontend/pull/2224 , marked with the [`dapp-connector`](https://github.com/Emurgo/yoroi-frontend/labels/dapp-connector) label, even tho they are not always related to the new cardano implementation, of course, but some are.

And look out please for future announcements for Cardano community devs as we gonna release nightly versions of the cardano-connector and ask the community for help testing it.

**Comment by cvetelinandreevdreamix** [comment]
> The implementation for the Cardano connector has already started, you can look out for PRs like #2213 and #2224 , marked with the [`dapp-connector`](https://github.com/Emurgo/yoroi-frontend/labels/dapp-connector) label, even tho they are not always related to the new cardano implementation, of course, but some are.
> 
> And look out please for future announcements for Cardano community devs as we gonna release nightly versions of the cardano-connector and ask the community for help testing it.

Hey @vsubhuman,

We have an existing iOS app which we want to integrate with a Cardano wallet. Basically we want to open a wallet app to sign a transaction we've prepared in advance. We'll use a testnet initially.

Is that possible now?

Will be there nightly builds for the iOS app we can test?

 Thank you!
