### ISSUE TITLE
Ethereum Dapps Issue

### ISSUE THREAD

**Issue by MahdiMbarki** [Emurgo/yoroi-frontend#2158]
Hello
i'm building an ethereum dapp Using truffle solidity ganache metamask react semantic-ui and next js 
but everytime i try following the steps provided on any tutorial I keep running into the same issues with node modules.
I am looking for recommendation on what version of node truffle and web3 I should use

**Comment by rdlrt** [comment]
Not sure how your query relates to Yoroi repository?

**Comment by MahdiMbarki** [comment]
turns out I was following some outdated tutorials.
