### ISSUE TITLE
Unknown pool from mobile version

### ISSUE THREAD

**Issue by efraservizi** [Emurgo/yoroi-frontend#2159]
Hello, delegators from mobile version reports unknown stake pool . Can please check what’s wrong couse meta seems ok 
Pool id: c9a397b8aa1d963030999d4edfd0f809f290f9899c73dfa1ad3a6d70

**Comment by setiamanlhc** [comment]
I have the same issue on both Chrome and Mobile (android). Delegated pool shown unknown.

**Comment by Straightpool** [comment]
See https://github.com/Emurgo/yoroi-frontend/issues/2164 for a properly documented issue.

**Comment by zuzunker** [comment]
Will be handled in https://github.com/Emurgo/yoroi-frontend/issues/2164
