### ISSUE TITLE
Unknow Pool on Web (Chrome) and Mobile

### ISSUE THREAD

**Issue by setiamanlhc** [Emurgo/yoroi-frontend#2163]
Hi,

My Pool Ticker is not showing correctly on the Yoroi wallet when delegated. It said unknow pool.
Here my Pool ID: 627a4ecacdc3d0e3fb5fe9a8cee8880a43069ec2f46d5217decef71c

![image](https://user-images.githubusercontent.com/1590866/120913166-75ad1100-c6c7-11eb-8170-6a6fcf7faf82.png)

Can advise how to resolve it ?

**Comment by Straightpool** [comment]
I created a properly documented issue here: https://github.com/Emurgo/yoroi-frontend/issues/2164

**Comment by setiamanlhc** [comment]
Somehow it resolves. Not sure if it is because I change the Blockchain Explorer in the chrome to ADAPOOLS.
