### ISSUE TITLE
Ledger shows the BECH32 Pool Id

### ISSUE THREAD

**Issue by zuzunker** [Emurgo/yoroi-frontend#2211]
From tweet: https://twitter.com/LEADStakePool/status/1411114501902979073

> On step 7 of the delegation process you display the Pool ID and tell the user to make sure it matches what is on the ledger - the ledger however shows the BECH32 Pool Id

**Comment by yushih** [comment]
Fix is at the `yoroi-extension-ledger-connect-vnext` repo.
