### ISSUE TITLE
Yoroi-dapp-connector 0.4.0 doesnt work with yoroi nightly 4.5.7001

### ISSUE THREAD

**Issue by deadit** [Emurgo/yoroi-frontend#2225]
Just download this two extensions at the chrome webstore and try to open yoroi-dapp-connector, you will see blank screen. No any errors in console.
https://chrome.google.com/webstore/detail/yoroi-ergo-dapp-connector/chifollcalpmjdiokipacefnpmbgjnle
https://chrome.google.com/webstore/detail/yoroi-nightly/poonlenmfdfbjfeeballhiibknlknepo
![image](https://user-images.githubusercontent.com/26635501/124996922-792f1180-e052-11eb-9cae-3c5b987e14bc.png)

Previously, it worked well yoroi-dapp-connector 0.4.0 version with 4.5.5001 version yoroi nightly.

**Comment by zuzunker** [comment]
Yoroi nightly `4.5.7002` is available now, the issue should be solved there
