### ISSUE TITLE
Yoroi Nightly crash on loading wallet

### ISSUE THREAD

**Issue by hodlonaut** [Emurgo/yoroi-frontend#2231]
MacOS 11.4, Chrome 91.0.4427

Log file attached
[yoroiNightlyCrash.log](https://github.com/Emurgo/yoroi-frontend/files/6812552/yoroiNightlyCrash.log)

**Comment by zuzunker** [comment]
Thank you, @hodlonaut! Was this with the nightly version `4.5.7002`?

**Comment by hodlonaut** [comment]
> Thank you, @hodlonaut! Was this with the nightly version `4.5.7002`?

Yep that's right, 4.5.7002.

**Comment by yushih** [comment]
Hi, @hodlonaut ! Thank you very much for reporting the issue. Do you mean the Chrome tab has crashed? And the log file is the Chrome debug log (https://support.google.com/chrome/a/answer/6271282)?

**Comment by hodlonaut** [comment]
Yes, the extension crashed (over and over and over, presumably can't cope with my testnet wallet) and I was presented with an option to reload it and not much in the way of 'see details of the crash', so I launched Chrome browser with debug log command line parameter and grabbed the information from that file that might or might not be useful.

**Comment by yushih** [comment]
@hodlonaut  sorry for what has happened and thank you very much for reporting the problem. However, the Chrome debug log didn't provide much insight into what Yoroi was doing that could cause Chrome to crash. I'm no expert in debugging Chrome but I'll keep an eye on the issue. Currently, I hope a newer version of Chrome would fix this. If you need to operate your wallet now, could you please try Yoroi for Firefox?

**Comment by hodlonaut** [comment]
Hi, what's the link for the Yoroi Nightly download/installation page for Firefox?

**Comment by yushih** [comment]
We only publish nightly for Chrome.

**Comment by hodlonaut** [comment]
So given my issue occurred on testnet, I cannot 'please try Yoroi for Firefox' suggestion of yours :)
You're welcome to provide me with an email address that I can send the testnet mnemonic of this wallet to, so you can hopefully reproduce the crash in-house and hopefully fix?

**Comment by yushih** [comment]
Could you please encrypt your testnet mnemonic with my public key and post the cipher here? Please run this in cli:
```
echo <testnet mnemonic in question> | openssl rsautl -encrypt -inkey <(echo -e '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2bZuud+GxgiVCpo7yWwx\nX9r24i1Mpm82hlQjcyAxWo0p+8I/tmYkF0fO22ajDx05DNasJIBpSDg8ls6NJD85\nRHNW0yBEbMtJANX0azenQchxJiONh5JMrf+iqirNzpF20bC9IxxuRaaDDRwH0JFd\nwpqV1v3wL72j2HP2Cn0921m5k7ssMc643Jo5QC0r8dHsRFFYNScr/3jrtoiaIVb2\n1T7L2hk30bGKQzZZwlL/Ct6jgOdzJwnXDohsj52WtyZe2azDb4Mbsz2yOPyNkhMo\n3/eMqusr9uM+gS08FkHYSIdqCHhrzV9QjXT+AE+csjSiXfQRdTLRFT0eGR6RJhgQ\nYwIDAQAB\n-----END PUBLIC KEY-----') -pubin  | openssl base64
```
(replace `<testnet mnemonic in question>` with the mnemonic)
and post the result here.
I will be able to decrypt your testnet mnemonic using my private key and debug. 
Thanks.

**Comment by hodlonaut** [comment]
EvPhCHMxYi/Gpvk05lc+Sr84Rz/0Z3VPxyy53iFAjYoU4WyrKC+oQhkQhOFxiis+
N68nfb68P71DNCoVHqv1+jDAV+U3RqJPzyCaoSRi4JQLWUUjHUAp0OdyoUqNGovp
B4+FSVVU+QGjykcuvBezbM0NqNtaQ5LgiyhWoGz4GBq+D1d4m1G4uvEsDPdWQWOZ
oh4cSRNuhClLYFAhGkJ4SxEc/Jlp5Am86azpzsOg+fHhzynH95bBKWKc4v1nZ6Q1
RNmmoCq3WKB5j++w0WpV3groJQq/vObjq9QQHq4AMHUOoFk1yUOQ5emPKyXEkvdx
py7yCQs13LjPZTiDWDZulg==

**Comment by yushih** [comment]
Thanks! Really appreciate your effort. I will investigate.

**Comment by zuzunker** [comment]
@hodlonaut, the new extension version 4.6 is now release and available in Chrome and Firefox. Can you please double-check if the issue got resolved there?

**Comment by hodlonaut** [comment]
Hi Ruslan

I can confirm that the Yoroi Nightly no longer crashes in Chrome for my testnet wallet, thanks for addressing that.

However, it is also very sluggish / barely usable with regards to the 'Send' functionality, again potentially due to the way a large number of tokens in the wallet is handled - I constantly get 'Unresponsive' pop-ups from Chrome while in Send screen and trying to change what token is being sent and what is it's quantity.

p.s. what is the link for Yoroi Nightly for Firefox?

**Comment by zuzunker** [comment]
> However, it is also very sluggish / barely usable with regards to the 'Send' functionality, again potentially due to the way a large number of tokens in the wallet is handled - I constantly get 'Unresponsive' pop-ups from Chrome while in Send screen and trying to change what token is being sent and what is it's quantity.

Thank you for the feedback! We will try to work on improving the performance for the big number of tokens.

> p.s. what is the link for Yoroi Nightly for Firefox?

Nightly is only being posted on Chrome atm
