### ISSUE TITLE
Typos in Complexity Level Form. + Language locales

### ISSUE THREAD

**Issue by Kirill-Johnson** [Emurgo/yoroi-frontend#2239]
1.
> I have **a some understanding** of blockchain and how cryptography is used to power both the blockchain itself **and wallet** software. I am okay with seeing options and functionality that critically depend on my understanding of these concepts.

I would change to:
> I have **some understanding** of blockchain and how cryptography is used to power both the blockchain itself **and the wallet** software. I am okay with seeing options and functionality that critically depend on my understanding of these concepts.

2.
> Your **currently** level of Complexity is

Change to:
> Your **current** level of Complexity is

3.
> Simplest experience possible. No previous knowledge **in Blockchain** required. Highly friendly to on-board beginners, and for users that prefer simplicity.

No one says "knowledge in blockchain" instead of "knowledge of blockchain", also not sure why "Blockchain" was capitalized here if you are referring to the concept in general.
> Simplest experience possible. No previous knowledge **of blockchain** required. Highly friendly to on-board beginners, and for users _who_ prefer simplicity.

Preferably I'd use "who" when referring to people, although "that" is not incorrect either.

4.
> **Understanding** blockchain can be difficult, which is why **we will try** and keep the interface as simple as possible for you

Would really sound better this way:
> **We understand** blockchain can be difficult, which is why **we try** and keep the interface as simple as possible for you

Frankly, I would rewrite some of the messages above even more, but I fixed the most obvious things.
***

It looks like these fixes should be added to ComplexityLevelForm.js, but a quick search shows that several locales contain that text as well. After a quick check in Yoroi, these messages display without translation for some of the languages (e.g. Korean).

By the way, after that quick check in Yoroi, I noticed some language locales are far from perfect (like section 12 of the Terms of Service hasn't been translated to at least a few languages I checked). Is that a bug or a feature, like the translations are still in progress?

**Comment by zuzunker** [comment]
Thank you, @Kirill-Johnson! 🙌  We will take care of those!
