### ISSUE TITLE
Theming broken on macOS with Brave Browser

### ISSUE THREAD

**Issue by galaxy-nomad** [Emurgo/yoroi-frontend#2254]
I am unable to implement custom themes on macOS with Brave Browser. I can customize the theme using the "inspect element" F12 option but I cannot export my changes or import them. The export button in the settings page does nothing at all in macOS. There is nothing saved in local storage (I think this applies to the windows platform only?) Any help implementing custom themes for macOS is much appreciated.

**Comment by cyberfunk** [comment]
Bump

**Comment by galaxy-nomad** [comment]
Never-mind I found a workaround!😁
