### ISSUE TITLE
How do I connect to testnet?

### ISSUE THREAD

**Issue by xptodevx** [Emurgo/yoroi-frontend#2258]
I can perfectly run on mainnet dev but I wanted to use it in the testnet. 
I'm trying to run the Chrome extension by the way.

**Comment by mmahut** [comment]
You need to use the Yoroi nightly.

**Comment by cheffNFT** [comment]
sorry, I have no idea how to do that. 
 i know that there's a file namely shelley-testnet.json but when I try to use it as
    "dev:nightly": "npm run dev:build -- --env 'shelley-testnet' --nightly",

I got some errors and plugin won't be loaded on chrome

`npm run dev:nightly

> yoroi@4.5.7 dev:nightly /Users/carlosbarros/Wise/yoroi-frontend/packages/yoroi-extension
> npm run dev:build -- --env 'shelley-testnet' --nightly


> yoroi@4.5.7 dev:build /Users/carlosbarros/Wise/yoroi-frontend/packages/yoroi-extension
> rimraf dev/ && babel-node scripts/build --type=debug "--env" "shelley-testnet" "--nightly"

[Build manifest]
--------------------------------------------------------------------------------
File manifest.development.json has been created
File manifest.mainnet.json has been created
File manifest.test.json has been created
[Copy assets]
--------------------------------------------------------------------------------
cp: no such file or directory: chrome/manifest.shelley-testnet.json
[Webpack Dev]
--------------------------------------------------------------------------------
If you're developing Inject page,
please allow 'https://localhost:3000' connections in Google Chrome,
and load unpacked extensions with `./dev` folder. (see https://developer.chrome.com/extensions/getstarted#unpacked)

Ergo connector ID set to chifollcalpmjdiokipacefnpmbgjnle
[webpack-httpolyglot-server] http(s)://localhost:3000
<i> [webpack-dev-middleware] wait until bundle finished: /js/__webpack_hmr
<i> [webpack-dev-middleware] wait until bundle finished: /js/__webpack_hmr
webpack built f4169b5fb603ac926124 in 43308ms
assets by info 9.12 MiB [immutable]
  assets by path *.ttf 1.17 MiB 10 assets
  assets by path *.otf 1.18 MiB 9 assets
  assets by path *.gif 142 KiB 6 assets
  assets by path *.wasm 4.31 MiB 4 assets
  assets by path *.png 2.32 MiB
    asset 5e955c4faa0b2abbed5a002e5a7f4a05.png 1.99 MiB [emitted] [immutable] [from: app/assets/images/paper-wallet/paper-wallet-certificate.front-min.png]
    asset 3cdf3519db3c7cb18539f51fc1a16056.png 334 KiB [emitted] [immutable] [from: app/assets/images/paper-wallet/paper-wallet-certificate.back-min.png]
assets by path *.js 73.8 MiB
  assets by chunk 27.8 MiB (id hint: vendors) 9 assets
assets by path ../*.html 3.89 KiB
  asset ../main_window.html 2.25 KiB [emitted]
  asset ../main_window_ergo.html 1.16 KiB [emitted]
  asset ../background.html 484 bytes [emitted]
Entrypoint yoroi 71 MiB (4.81 MiB) = 19 assets 27 auxiliary assets
Entrypoint background 13.8 MiB = vendors-node_modules_babel_runtime-corejs3_core-js-stable_array_from_js-node_modules_babel_ru-b0573b.bundle.js 9.71 MiB app_api_common_index_js-app_api_common_migration_js-app_api_ergo_lib_state-fetch_batchedFetch-59b76f.bundle.js 3.78 MiB background.bundle.js 311 KiB
Entrypoint ergo 32 MiB (4.67 MiB) = 7 assets 21 auxiliary assets
runtime modules 182 KiB 54 modules
orphan modules 50.2 KiB [orphan] 47 modules
modules by path ./node_modules/ 9.46 MiB (javascript) 4.31 MiB (webassembly)
  javascript modules 9.31 MiB 2085 modules
  json modules 154 KiB 11 modules
  webassembly modules 745 bytes (javascript) 4.31 MiB (webassembly) 4 modules
modules by path ./app/ 17.4 MiB
  javascript modules 16.2 MiB
    cacheable modules 16.2 MiB 1367 modules
    4 modules
  json modules 1.19 MiB 19 modules
modules by path ./chrome/ 86.7 KiB
  modules by path ./chrome/extension/ 68.8 KiB 6 modules
  modules by path ./chrome/*.js 17.8 KiB 4 modules
9 modules

WARNING in ./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib_bg.js 8628:14-53
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib.js 2:0-50 2:0-50
 @ ./app/api/ada/lib/cardanoCrypto/rustLoader.js 21:25-102
 @ ./chrome/extension/background.js 25:0-76 177:18-33 562:20-35 563:49-69 586:20-35 587:49-69 715:20-35 716:55-75

WARNING in ./node_modules/@emurgo/js-chain-libs/js_chain_libs.js 4507:14-53
Critical dependency: the request of a dependency is an expression
 @ ./app/api/ada/lib/cardanoCrypto/rustLoader.js 20:25-70
 @ ./chrome/extension/background.js 25:0-76 177:18-33 562:20-35 563:49-69 586:20-35 587:49-69 715:20-35 716:55-75

2 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.23.0 compiled with 2 warnings in 43308 ms`
