### ISSUE TITLE
Yoroi Web UI does not show decimals for Native Tokens (Mobile UI does)

### ISSUE THREAD

**Issue by EnricoSaunders** [Emurgo/yoroi-frontend#2286]
After adding native token metadata with decimals to the registry (cardano-foundation/cardano-token-registry), the web (Chrome Extension) wallet does not show the decimals in the transaction or the send form. The amount field of the send form just removes the decimals as you try to type them.

**Expected behaviour:**
The Android Wallet UI has the correct behaviour where it shows the decimals in the transaction details and allows you to enter decimals in the Amount field of the send Form. The amount field validation correctly displays an error when you try to type more decimals than are valid.

**Comment by EnricoSaunders** [comment]
Closing as the chome extension works as expected now. 
I see it was fixed in https://github.com/Emurgo/yoroi-frontend/releases/tag/4.6.0

**Comment by yushih** [comment]
Thanks @EnricoSaunders !
