### ISSUE TITLE
22/01/19 Yoroi Developers Meeting Agenda

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/yoroi-frontend#235]
Add topics in this issue that you think should be brought up during our weekly developer meeting.
Please have one post / person

**Time**: 2:00-3:00pm JST
Meeting link: https://hangouts.google.com/hangouts/_/my6ukpd2svhbbfe52jtfvqjpm4e

**Tentative Agenda**:
- [Discuss issues under triage](https://github.com/Emurgo/yoroi-frontend/pulls?q=is%3Apr+label%3A%22new+scenario+%28desired%29%22+sort%3Aupdated-desc+is%3Aopen)
- [PRs merged this week](https://github.com/Emurgo/yoroi-frontend/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+merged%3A%3E2019-01-14+)
- Individual progress updates

[Previous week](https://github.com/Emurgo/yoroi-frontend/issues/181)

**Comment by SebastienGllmt** [comment]
- Release candidate to QA
- Firefox release
- German support (#236 )

**Comment by sarveshwar-singh** [comment]
- https://github.com/Emurgo/yoroi-frontend/issues/251

**Comment by SebastienGllmt** [comment]
Recording [can be found here](https://www.youtube.com/playlist?list=PLFLTrdAG7xRbIWoyb9sGOgrzcA3_DRrtN)
