### ISSUE TITLE
"Show on Trezor" feature for Trezor Integrated wallet

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#237]
"Show on Trezor" feature let you check the generated receiving address 
on your Trezor device to make sure that receiving address you have 
provided to someone else has not been changed by the infected 
computer.   You can try the feature in Trezor Wallet 
(https://wallet.trezor.io) under "Receive" section - "Show full address" 
button.

**Comment by SebastienGllmt** [comment]
We added this a while back (part of 1.4 release) so I'm closing this.
