### ISSUE TITLE
Recovery phrase verification cannot proceed when a word is repeated

### ISSUE THREAD

**Issue by nkishi** [Emurgo/yoroi-frontend#2380]
I was unable to verify the recovery phrase due to a word it contained twice. The repeated word appeared twice in the list of words to order, however, both instances of the word disappeared from the pick list at the first selection attempt, blocking the verification process.

**Comment by zuzunker** [comment]
Hi @nkishi! Thank you for the report! Was this in the browser extension or in the mobile app?

**Comment by nkishi** [comment]
The Android mobile app (4.3.0). Please ignore, I should have checked the [yoroi-mobile issues](https://github.com/Emurgo/yoroi-mobile/issues/1566) .

**Comment by zuzunker** [comment]
No problem, thank you for reporting! We'll try to get this fixed in the nearest update. Meanwhile the workaround would be to restart the wallet creation from step one yo get new words and make sure they don't have duplicates. Really sorry for this inconvenience
