### ISSUE TITLE
Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)

### ISSUE THREAD

**Issue by jmhoms** [Emurgo/yoroi-frontend#2423]
Hi,

I'm having problems to restore a particular Shelley standard wallet in Yoroi, and I think it may be because of a bug. I tried to restore the same wallet using clean Firefox and Chromium installations with the same result, Yoroi keeps trying to sync forever. Please note that I'm able to import other Shelley standard wallets without a problem in these same browsers/Yoroi. Also be aware that I successfully imported this "problematic" wallet using Yoroi for IOS. Please see below the error message that keeps repeating in the log:

[INFO] Yoroi v.4.7.400
[INFO] Commit: 64ae9837afe3347f8ae7d7af0b8ec98d03e2a1c2
[INFO] Network: mainnet
[INFO] User Agent: { ua: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
  browser: { name: 'Chrome', version: '90.0.4430.212', major: '90' },
  engine: { name: 'Blink', version: '90.0.4430.212' },
  os: { name: 'Linux', version: 'x86_64' },
  device: { vendor: undefined, model: undefined, type: undefined },
  cpu: { architecture: 'amd64' } }
----
[2021-09-29T01:35:59+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-09-29T01:35:59+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "l: api.errors.GenericApiError: undefined
    at Te.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:3111)
    at async i._method (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_ef4bde61.bundle.js:1:145790)",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}

Do let me know if you need any additional info.

Cheers!

**Comment by benapetr** [comment]
I am having similar issues in https://github.com/Emurgo/yoroi-frontend/issues/2448

**Comment by benapetr** [comment]
it seems this is a problem every time I try to import my HARDWARE wallet - software wallet I imported in the past works just fine. It's Ledger S, which doesn't seem to work. It did work in the past but suddenly, probably since some Yoroi update it stopped.

**Comment by scratchy** [comment]
having exactly this crap as well.. Breaks my whole yoroi wallet with my ledger..

**Comment by zuzunker** [comment]
> having exactly this crap as well.. Breaks my whole yoroi wallet with my ledger..

Which Yoroi and Ledger Cardano App versions?

**Comment by scratchy** [comment]
ledger has latest cardano app (but its not even connected, since i importet the public key long time ago..)

yoroi chrome version is 4.8.0 also this error blocks the whole sync process of those wallets. Resync of those via settings does not help at all.

heres some console output.
![grafik](https://user-images.githubusercontent.com/906544/144928148-085e12c2-4043-4372-b394-55edcb18a59e.png)

**Comment by benapetr** [comment]
getting same error in Firefox

**Comment by mtracy** [comment]
I also get this error with yoroi 4.8.1 with ledger on chrome. Tried updating ledger, and removing/readding the wallet in yoroi.
