### ISSUE TITLE
Unwanted text in Japanese Terms of Service

### ISSUE THREAD

**Issue by Leo-Emurgo** [Emurgo/yoroi-frontend#244]
@sarveshwar-singh 

There is a translator's note in the Japanese-language terms of service that needs to be deleted. 
It is under heading 3. The unwanted text is as follows. Please delete this text, leaving everything else intact. 

【AMT：18歳は含まれないことを念のためご確認ください。】

**Comment by SebastienGllmt** [comment]
Fix by #273
