### ISSUE TITLE
Fix onClick in TrezorSendConfirmationDialog

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#245]
Similar to: https://github.com/Emurgo/yoroi-frontend/pull/242

**Comment by vantuz-subhuman** [comment]
Fixed in https://github.com/Emurgo/yoroi-frontend/pull/242

**Comment by vantuz-subhuman** [comment]
Closed by accident. Issue similar to one in #242, but for Trezor

**Comment by sarveshwar-singh** [comment]
Fixed In: https://github.com/Emurgo/yoroi-frontend/pull/246
