### ISSUE TITLE
Export transaction CSV with transaction id

### ISSUE THREAD

**Issue by goriunov** [Emurgo/yoroi-frontend#2453]
Hello,

I have noticed that csv transactions exported to the csv file for tax purposes do not include transaction id. Is there any plan to add it ? Or may be there are any reason not to add it ?

**Comment by zuzunker** [comment]
Hi, @goriunov! Yeah, we really were kinda also looking that we probably need to add it. Even more reason to do so now that we have this issue opened 👍

**Comment by zuzunker** [comment]
We gonna make it optional though, as, if I recall correctly, privacy was the main reasoning to not add them by default. E.g. you might want to have a report of all your TXs up to this point, but sharing tx IDs techncially allows the receiver to know and track your entire address set used up to this point and to find out all the UTxOs you have at that moment.

**Comment by goriunov** [comment]
Agree this could be as optional parameter, the reason why i thought it could be important at least for some people (including myself) is to be compliant with tax rules (at least in nz) and keeping track of all the transactions for potential auditing. :)
