### ISSUE TITLE
Not enough funds to make this transaction error

### ISSUE THREAD

**Issue by silaslang** [Emurgo/yoroi-frontend#2457]
I am having major issues trying to move ada . In a wallet with 8 ada I try to send 5 to another wallet and it says Not enough funds to make this transaction'.

It happens in other wallets aswell with varying amounts of ada, one has 124 ada and lots of NFTS and I cant send ada out the wallet. 

Anyway to resolve this?

**Comment by zuzunker** [comment]
Hi, @silaslang ! How many different token types or NFTs you have in the wallet with 8 ADA?

Are you using the browser version? Check the "Locked assets deposit" value under the wallet balance in the topbar.

See this document for reference: https://github.com/Emurgo/yoroi-frontend/blob/develop/docs/readme/cardano-token-deposit-explained.md

**Comment by zuzunker** [comment]
Closing in assumption that the previous comment has resolved the issue. From my side can only add that we are actually in the middle of the Yoroi redesign at the moment and in the new version we will try to make all this information much more visible and transparent.
