### ISSUE TITLE
Ledger Cardano app 3.0.0 not connecting with Yoroi

### ISSUE THREAD

**Issue by goetzc** [Emurgo/yoroi-frontend#2466]
When trying to connect a Ledger with a newly update firmware, Yoroi fails to establish a connection. Before the firmware and app upgrade this was working.

On the Firefox console this error is shown.

```js
LedgerLocalizedError::convertToLocalizableError::error: {
  "fileName": "moz-extension://<REDACTED>/js/159.bundle.js",
  "lineNumber": 2,
  "columnNumber": 5498,
  "message": "Device app version unsupported. Please upgrade to 2.3.2."
}
```
On the GUI there only this message is shown "`Something unexpected happened. Please retry`".

## Versions

- Firefox: 93.0
- Yoroi extension: 4.7.400.0
- Ledger Nano X:
  - Secure Element: 2.0.0
  - Microcontroller: 2.28
  - Bootloader: 1.16
  - Cardano app: 3.0.0

-----

<small>Edit: Same device works using adalite.io.<small/>

**Comment by goetzc** [comment]
Looks like there was some strange not-so-compatible version, as on Ledger Live there is an "update" to 2.4.1 (from 3.0.0) which makes Yoroi connection to the device work again.

**Comment by AraxesTharsis** [comment]
I have the same problem, as I can't access my Yoroi wallet with the Ledger S Cardano ADA app v3.0.0. Where is the option in Ledger Live to downgrade the Cardano ADA app to v2.4.1?

**Comment by vsubhuman** [comment]
This is fixed in version 4.5 , which is about to be pushed to release

**Comment by zuzunker** [comment]
This should be resolved in the version 4.8 which is already available on Firefox and is going through the store review in Chrome and Edge

**Comment by zuzunker** [comment]
Version 4.8 is now available in Firefox and Chrome (check if it has updated in your browser), confirm if the issue still exists please

**Comment by AraxesTharsis** [comment]
I confirm that, for me, everything is back to working normally with Yoroi 4.8 in Chrome.
Thank you very much!

**Comment by zuzunker** [comment]
> I confirm that, for me, everything is back to working normally with Yoroi 4.8 in Chrome. Thank you very much!

Thank you!
