### ISSUE TITLE
All my ADA has disappeared from Yoroi wallet

### ISSUE THREAD

**Issue by adroFPV** [Emurgo/yoroi-frontend#2468]
Hi, last night i bought some NFTs from a legit source. Now all my ADA has disappeared from my wallet. 

Please advise what you need as i believe wallet address is not permanent right? 

Does this help?
addr1q8k5zk8ulh07d8pxwmmntrvwryz6ahartt049ng327705jn8k279wd7q0f7zhq6qrfq6aw3gfy8aa6p7457q0uz8gsyq6mmejg

**Comment by zuzunker** [comment]
Hi, @adroFPV, you mind sending a screenshot of your transaction history page and the wallet balance?

**Comment by adroFPV** [comment]
It’s appeared all of a sudden now…

Any idea why?

A

**Comment by zuzunker** [comment]
Hmmm, might potentially be some lag with how the utxos are processed on the frontend. We'll look into it, but glad everything is good at the end.
