### ISSUE TITLE
update obsolete engineStrict

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#249]
https://docs.npmjs.com/files/package.json#enginestrict

**Comment by nicarq** [comment]
So `engine` -> `engines` and delete `engineStrict`

**Comment by sarveshwar-singh** [comment]
I think:

- From
```
  "engineStrict": true,
  "engine": {
    "node": "~8.9.4",
    "npm": "~5.6.0"
  }
```
- To
```
  "engine-strict": true,
  "engines": {
    "node": "~8.9.4",
    "npm": "~5.6.0"
  }
```

https://docs.npmjs.com/files/package.json#engines
We have two bugs to solve:
1. `engine` -> `engines`
2. `engineStrict` -> `engine-strict`
