### ISSUE TITLE
store restructuring WalletBackupStore

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#251]
WalletBackupStore: https://github.com/Emurgo/yoroi-frontend/blob/develop/app/stores/toplevel/WalletBackupStore.js
Since WalletBackupStore is a part of wallet creation process and wallet creation process is handled by https://github.com/Emurgo/yoroi-frontend/blob/develop/app/stores/ada/AdaWalletsStore.js

Then logically WalletBackupStore should be inside https://github.com/Emurgo/yoroi-frontend/tree/develop/app/stores/ada

**Comment by SebastienGllmt** [comment]
This is by design I believe and also not needed since we'll be moving to Redux anyway.
