### ISSUE TITLE
An error occurred while trying to connect with your hardware wallet

### ISSUE THREAD

**Issue by TheoMer** [Emurgo/yoroi-frontend#2510]
1. Nano X firmware 2.0.0
2. Yoroi version 4.4.0
3. iOS 15.0.2

I receive the above specified error when attempting to verify an address or withdraw rewards.

What is the issue here?

**Comment by TheoMer** [comment]
![IMG_3111](https://user-images.githubusercontent.com/15969262/140304633-359682a2-ec56-405c-8d0f-4c3b59ed04cf.PNG)

**Comment by TheoMer** [comment]
My ledger nano x works seamlessly with the Yoroi chrome plugin,but is unusable with Bluetooth on iOS (6S plus).

**Comment by Ltadrian** [comment]
I don't get this error on chrome, but I land on a page that says to accept the public key code and nothing happens when I do accept from the ledger. The ledger switches to waiting for commands and nothing happens on the web page.
Brave/Chromium:  Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)

**Comment by zuzunker** [comment]
Try it please with the browser version **4.8** it should not have any problems, afaik. In the mobile the new release **4.5** is just about to go out right at the moment and it will have the Ledger compatibility fix in it as well

**Comment by TheoMer** [comment]
iPhone: 13 Pro Max.  
iOS: 15.2.  
Yoroi: 4.5 

Cc @vsubhuman 

I just tried the new version of Yoroi and am still having issues. Please see attached image.


![image](https://user-images.githubusercontent.com/15969262/146203794-166fdbbe-ccda-4049-9d55-95318ab3be7a.jpeg)

**Comment by zuzunker** [comment]
Investigating

**Comment by zuzunker** [comment]
Fix for this is prepared, new version 4.5.2 is being released today. Might take a day or two to go through the stores

**Comment by zuzunker** [comment]
A Ledger wallet might need to be removed from Yoroi and reconnected again after updating to the 4.5.2, this must be solving the issue reliably

**Comment by Nebyt** [comment]
@vsubhuman @TheoMer Do I right understand the issue https://github.com/Emurgo/yoroi-frontend/issues/2510 is a sibling of this issue?

**Comment by TheoMer** [comment]
> @vsubhuman @TheoMer Do I right understand the issue https://github.com/Emurgo/yoroi-frontend/issues/2510 is a sibling of this issue?

That's correct. I raised a separate issue just incase I had not followed proper procedure by initially raising it in this thread.

**Comment by TheoMer** [comment]
> Fix for this is prepared, new version 4.5.2 is being released today. Might take a day or two to go through the stores

Excellent 👍🏽

**Comment by Nebyt** [comment]
> > @vsubhuman @TheoMer Do I right understand the issue #2510 is a sibling of this issue?
> 
> That's correct. I raised a separate issue just incase I had not followed proper procedure by initially raising it in this thread.

Sorry for the inconvenience, I mean the issue https://github.com/Emurgo/yoroi-frontend/issues/2578

**Comment by TheoMer** [comment]
@Nebyt Yes #2578 is the issue I was referring to.

**Comment by TheoMer** [comment]
@vsubhuman All appears to be working fine now  👍🏽
