### ISSUE TITLE
Improve tests part (for chrome) of README for first contributions/contributors

### ISSUE THREAD

**Issue by chisNaN** [Emurgo/yoroi-frontend#253]
Hello.
Maybe there is a part where tests are better described on how to be accomplished but 
if i take the readme as it is in its actual version i have already several observations:

- 1)  tests must be launched like this (for chrome)

`npm run test-by-feature-chrome features/wallet-creation.feature`

and not ~npm run test-by-feature feature/wallet-creation.feature~

- 2)  If the extension is not packed as a `.crx` file with name `yoroi-test.crx` as it is called at line 37 of the `webdriver.js` file it will give this error:

`Error: ENOENT: no such file or directory, open '/Users/art/Documents/yoroi-frontend/yoroi-test.crx`

So I packed the extension from `dev/` folder and renamed `yoroi-test.crx`

- 3) Still the test wont work "FOR ME", because the following ID `bdlknlffjjmjckcldekkbejaogpkjphg`
as "hardcoded" at the line 86 of the same file `webdriver.js` is not allowed or something like this (see the screenshot sorry its french default).

<img width="945" alt="capture d ecran 2019-01-22 a 15 11 58" src="https://user-images.githubusercontent.com/2439389/51541443-1b45e980-1e59-11e9-9391-28a4f3d0c1a4.png">

And if i eventually replace the id of this URL:
`chrome-extension://bdlknlffjjmjckcldekkbejaogpkjphg/main_window.html`

with the id of my yoroi extension for dev purpose like this:

`chrome-extension://bflmcienanhdibafopagdcaaenkmoago/main_window.html`

The test on the browser will be processed but the terminal will be stuck in retrying to launch the test with the other id.

Any help would be welcomed. I guess its just additional documentation.

Thanks in advance.

**Comment by SebastienGllmt** [comment]
you have to run `npm run test-prepare` to generate the `yoroi-test.crx`. I think maybe the confusion is because the instruction telling you to do this [here](https://github.com/Emurgo/yoroi-frontend#test) is after "command to run all existing tests" but you actually have to run `test-prepare` before running any tests

**Comment by chisNaN** [comment]
Oh thanks sebastien  that's it
Something telling me to launch all tests was scaring me.
