### ISSUE TITLE
List of Addresses not updated when transacting from a different session

### ISSUE THREAD

**Issue by rdlrt** [Emurgo/yoroi-frontend#254]
I suppose the behaviour is known, but just to document to issue list. The list of addresses is not fetched correctly if an outgoing transaction is made from a foreign session.

Steps to Replicate:
1. Open same wallet in 2 browsers:
![image](https://user-images.githubusercontent.com/3169068/51588611-d85b4300-1f38-11e9-8783-58204b48c8f2.png)

2. Perform an outgoing transaction from one session:
![image](https://user-images.githubusercontent.com/3169068/51588670-ee690380-1f38-11e9-99fd-dfe6884afcdb.png)

3. The change address is only added to active session, not the inactive one:
![image](https://user-images.githubusercontent.com/3169068/51588678-f7f26b80-1f38-11e9-83d4-2479d654b366.png)

4. Clear Local Storage OR clean extension cache OR reinstall yoroi is required to extract the correct address list again:
![image](https://user-images.githubusercontent.com/3169068/51588932-9252af00-1f39-11e9-8d18-4f26c780eae2.png)
![image](https://user-images.githubusercontent.com/3169068/51588934-95e63600-1f39-11e9-820a-98feb0537e8d.png)

**Comment by SebastienGllmt** [comment]
Closing as this is fixed by #322
