### ISSUE TITLE
tx status is showing Failed when is not.

### ISSUE THREAD

**Issue by stakelovelace** [Emurgo/yoroi-frontend#2564]
![photo_2021-12-09_16-23-48](https://user-images.githubusercontent.com/56354546/145435359-20e02d6b-28ee-46c1-a504-96ced7458d9f.jpg)

**Comment by zuzunker** [comment]
Hi! Refer plz to this issue and this comment there: https://github.com/Emurgo/yoroi-frontend/issues/2552#issuecomment-986756378

I will close this one because it's a full duplicate, subscribe plz to that other issue if you wish to receive notifications on the progress.
