### ISSUE TITLE
Error: ledgerUtils::connectionHandler debiceObj is null

### ISSUE THREAD

**Issue by TheoMer** [Emurgo/yoroi-frontend#2578]
Nano X firmware 2.0.0.  
Yoroi version 4.5.  
iOS 15.2.  
iPhone: 13 Pro Max.  

When attempting to verify an address I get the above mentioned error. See attached image.

![image](https://user-images.githubusercontent.com/15969262/146213376-61a15c78-45fe-4ad1-bc94-8aa791bf91ce.jpeg)

**Comment by zuzunker** [comment]
This should be fixed in latest mobile version 4.5.2
