### ISSUE TITLE
Yoroi extension not loading in Chromium

### ISSUE THREAD

**Issue by Smedzlatko** [Emurgo/yoroi-frontend#2587]
Recently, Yoroi updated itself to version to version 4.8.3 and stopped loading at all in my browser. It simply displays Yoroi logo with `loading components` spinner underneath. The spinner disappears after couple of seconds but nothing is loaded and only the logo is visible on the page.

I am using Brave 1.33.106 based on Chromium 96.0. I tried this on Chromium 96.0 without any adblock extensions as well and I am having the same issue.

**Comment by Smedzlatko** [comment]
Fixed by cleaning all my caches. Sorry for bad report.

**Comment by zuzunker** [comment]
> Fixed by cleaning all my caches. Sorry for bad report.

Thank you for reporting!
