### ISSUE TITLE
"About Yoroi" section in settings

### ISSUE THREAD

**Issue by vantuz-subhuman** [Emurgo/yoroi-frontend#263]
## Problem

Can't see current Yoroi version and various stuff about it anywhere in UI (need to go to Chrome app management page for this).

## Abstract

We need a section where we can put any kind of info stuff about the app, but that would not be interfering with the main UX much.

## Idea

Create a special section "About Yoroi" in settings, and put this idea there:

1. Current version as link to changelog (e.g. "Yoroi version: [1.2.0](https://github.com/Emurgo/yoroi-frontend/releases/tag/1.2.0)")
2. Link to website: https://yoroi-wallet.com
3. Link to Emurgo blog: https://medium.com/@emurgo_io
4. Link to twitter: https://twitter.com/YoroiWallet
5. Link to GitHub: https://github.com/Emurgo/yoroi-frontend
6. Playlist about Yoroi on Emurgo YT: https://www.youtube.com/watch?v=GLNgpr-3t2E&list=PLFLTrdAG7xRZUmi04s44T1VEF20xKquF2
7. Link to community help channel: https://t.me/CardanoCommunityTechSupport

## UI

Because the "General" section in settings is very small atm and there's only the language selector - I would propose to add a text section on top there:

![image](https://user-images.githubusercontent.com/5585355/51801396-0ea50500-224e-11e9-8579-00c8b8fb1c57.png)

Section just similar to how it looks in "Support":

![image](https://user-images.githubusercontent.com/5585355/51801405-40b66700-224e-11e9-8d9c-da3fc30a0e96.png)

But with all the links instead.

If ever we got more settings for the "General" section - we can move "About" to it's own menu-item.

**Comment by vantuz-subhuman** [comment]
Suggest any additional info we need to put there, plz

**Comment by adamparish** [comment]
Great idea! This will make the user feel much more confident with the Yoroi Wallet.

**Comment by sarveshwar-singh** [comment]
https://github.com/Emurgo/yoroi-frontend/pull/305
