### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by voidzero** [Emurgo/yoroi-frontend#2656]
Vivaldi:	5.0.2497.32 (Stable channel) (64-bit)
Revision:	4891cb2a30270ebb895cf22eb99642090bde0046
OS:	Windows 10 Version 21H1 (Build 19043.1466)
JavaScript:	V8 9.6.180.21
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36

Hello,

The font in this size causes all letter 'c' to look like an 'o'. I have looked in DevTools, the font should be Rubik, but I'm not sure if this is actually Rubik. Please see the attachment. When I increase the zoom the font increases and the problem goes away. It's not just here, but also in all texts (for example, under "Total Rewards" it looks like it says "less than expeoted?"

Thank you,
Mark

![yoroi font](https://user-images.githubusercontent.com/1332504/149521418-eaeec787-b64c-4e7a-a2d3-3ce56822ba4c.jpg)

**Comment by yushih** [comment]
This is not fixed by https://github.com/Emurgo/yoroi-frontend/pull/2599?

**Comment by voidzero** [comment]
I'm on 4.9.3. So it doesn't look like it.

**Comment by yushih** [comment]
Thanks for reporting this! What is the "render fonts" of the text where "c" is like an "o" (https://stackoverflow.com/questions/35522797/why-does-chrome-developer-tools-computed-tab-mention-the-rendered-font-to-be-a-d) ?

**Comment by voidzero** [comment]
I do not see that in the developer tools window for Yoroi. I do see it for example on this github page so. Not sure what to make of it. Screenshot attached.
![image](https://user-images.githubusercontent.com/1332504/150176468-b2d6d8f3-4e15-46eb-b509-c98056173e4b.png)

**Comment by voidzero** [comment]
Scratch that. I had to select the element first.

The font is Rubik. Screenshot:

![image](https://user-images.githubusercontent.com/1332504/150176941-ad633ee7-3bba-4536-a379-cb6224fc0905.png)

**Comment by yushih** [comment]
Thanks a lot! @voidzero !

**Comment by voidzero** [comment]
Thank you @yushih. Hope it helps!

**Comment by pizzadudez** [comment]
I was just about to post about a typo but it seems this font issue is the culprit
