### ISSUE TITLE
Syncing problem/can't delegate

### ISSUE THREAD

**Issue by ccm92** [Emurgo/yoroi-frontend#2667]
Hi, my wallet last synced 5 days ago and i can't delegate to a new delegator. Im using chrome
![ss](https://user-images.githubusercontent.com/97863386/149701467-753d03c1-dbd4-4669-a777-ac02ae9accab.jpg)

**Comment by zuzunker** [comment]
Hi! What happens when you open one of these wallets and wait for a while? Does it update the time it last synced?

**Comment by ccm92** [comment]
Hi, the last sync never updates even if I open the wallet and let it sit
for a long time. The rewards section receives an error, and when I click on
"DELEGATE button" it will process for a bit and then disappear and nothing
happens. Please see files attached. thanks

**Comment by zuzunker** [comment]
An update to all our backends is being done at the moment and will be finished in an hour or so. After that time check please again if your wallets are syncing better

**Comment by ccm92** [comment]
Awesome man, thank you for working on it asap, it finally synced!
