### ISSUE TITLE
windows development/debug setup

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#267]
The basic Idea is to able to build/test/debug(everything) in pure windows environment.
by using Windows Subsystem for Linux, build works well but not everything.

**Comment by Mercurial** [comment]
just some info here on my experience, I easily setup a windows development environment with Windows Subsystem for Linux (basically bash on windows) 

you will need Windows 10 Pro but its really good for anyone looking at yoroi development on windows

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by sarveshwar-singh** [comment]
@Mercurial 
Have updated the initial comment.

**Comment by SebastienGllmt** [comment]
I think WSL is super easy to use now-a-days so we no longer need this.
