### ISSUE TITLE
Wallets do not sync.

### ISSUE THREAD

**Issue by rohitwritescode** [Emurgo/yoroi-frontend#2671]
Hi team,

I am having issues with my wallets syncing. They have been in this state for a couple of days now.

![image](https://user-images.githubusercontent.com/80547800/149857157-3725b8ac-3144-4afc-bb9c-2befb98b205d.png)

I tried re-syncing both wallets to the blockchain, but that doesn't seem to work either.

Hoping to have this issue fixed so that I can delegate more of my ADA to a stake pool ahead of the SundaeSwap ISO.

Thank you.

**Comment by neuodev** [comment]
Hi, @rohitwritescode 
there is a problem with the `Wallets Sycning` functionality (Backend). Currently working on fixing it.

**Comment by rohitwritescode** [comment]
Hi @AhmedIbrahim336 ,

Thank you for the update.

I will wait for a fix in that case.

**Comment by rohitwritescode** [comment]
Just checked, and my wallets seem to be syncing and everything looks good. Thanks for looking into this! Good luck to the team!
