### ISSUE TITLE
Dapp Connector Collateral

### ISSUE THREAD

**Issue by edu-d-rai** [Emurgo/yoroi-frontend#2708]
Ey guys, both Nami and CCvault have a getCollateral method, it's important for Dapp interaction, I know that it's not on the CIP0030 but is it on the roadmap to implement this function?
Do you have any suggestion about how to handle this?

**Comment by zuzunker** [comment]
It's currently being implemented in Yoroi , along with getting this change in - https://github.com/cardano-foundation/CIPs/pull/208.

Will be available in the next version

**Comment by cardahub-dev** [comment]
@vsubhuman we managed to filter the available utxos to get one for the collateral. But if that utxo is in a different address with the ones in the transaction input, it will not be signed. Hope that would also be addressed in the next release, e.g., also sign the input in the collateral.

**Comment by zuzunker** [comment]
> @vsubhuman we managed to filter the available utxos to get one for the collateral. But if that utxo is in a different address with the ones in the transaction input, it will not be signed. Hope that would also be addressed in the next release, e.g., also sign the input in the collateral.

Yes, it is being implemented

**Comment by rosieks** [comment]
I think that current implementation does not follow standard and the function is called `getCollateralUtxos` while standard says about `getCollateral`

**Comment by zuzunker** [comment]
> I think that current implementation does not follow standard and the function is called getCollateralUtxos while standard says about getCollateral

This is already fixed in the latest available version
