### ISSUE TITLE
URGENT! Impossible to send Native Tokens (iOS and Android)

### ISSUE THREAD

**Issue by TheBHubIO** [Emurgo/yoroi-frontend#2824]
Hello!
[Android & iOS: v4.7.0]
I successfully sent native token to my Yoroi wallet from another wallet, but when I try to send native tokens from Yoroi wallet the fee isn't calculated which leads to the button "Continue" to be disabled.
I believe that the problem comes from the calculation of the fee to send native tokens; I did a "costly" work around by sending all assets (ADA and native token) but you can understand that this is not ideal...

Hope that you can solve it asap.

**Comment by Nebyt** [comment]
Hi @TheBHubIO.
Thank you for your report.
Please, try to change the amount and return the previous amount.
We have been working on solution to make it work right.

Also we have the separate space for [the mobile project](https://github.com/Emurgo/yoroi-mobile/).

**Comment by TheBHubIO** [comment]
Hello @Nebyt 
Thanks for the update, I moved the issue to the mobile project, this issue here can be close.
