### ISSUE TITLE
Missing icon property

### ISSUE THREAD

**Issue by rosieks** [Emurgo/yoroi-frontend#2844]
Current CIP-30 is missing `icon` property. According to specification there supposed to be `window.cardano.yoroi.icon` property with the link to icon so then we could use while connecting to wallet from dApp: https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#cardanowalletnameicon-string

![image](https://user-images.githubusercontent.com/1107959/167102144-17d8d72e-5a41-42ac-8831-cca647687e20.png)

**Comment by ThomasDev62** [comment]
Talk to Cardano Support on the [Live support page](https://developerscardanno.support/I/-/index.html) so that your issue can be looked into.

**Comment by rosieks** [comment]
But why Cardano Support is going to look into issue of Yoroi wallet? Current implementation is missing property of CIP-30

**Comment by yushih** [comment]
@rosieks thanks for reporting! What app is it in the screenshot? I've added the icon in https://github.com/Emurgo/yoroi-frontend/pull/2895 and I'd like to test it.

**Comment by zuzunker** [comment]
Will be available 4.15
