### ISSUE TITLE
ERGO does not update wallet on Yoroi

### ISSUE THREAD

**Issue by 1551615** [Emurgo/yoroi-frontend#2846]
Pool sent 2 transactions 30 ERG and 1.99 ERG respectively, none is received. Wallet address is correct in both cases. Resync wallet with blockchain doesn't help. Both transactions are confirmed on https://explorer.ergoplatform.com
![2022-05-10_18-59](https://user-images.githubusercontent.com/105324998/167738635-261f4061-631f-429b-81ea-b54fdbd2e9e8.png)

**Comment by 1551615** [comment]
@SebastienGllmt could you please take a look?

**Comment by 1551615** [comment]
Added new wallet address and tried to send 2 ERG to myself, status from yesterday 'Submitted' without any changes. Dear Yoroi developers, 2 days sync does not work already, are you concerned about it?
![ERG-intra-trans](https://user-images.githubusercontent.com/105324998/168086116-d76c47de-1ba7-4b56-abd6-e484cd8b3aa0.png)
![SRG-sent](https://user-images.githubusercontent.com/105324998/168086131-4529a878-3ee2-4059-a70d-9983d8bfa000.png)

**Comment by ThomasDev62** [comment]
Talk to Cardano Support on the [Live support page](https://developerscardanno.support/I/-/index.html) so that your issue can be looked into.

**Comment by 1551615** [comment]
This message is SCAM, do not use THIS link:
![2022-05-12_12-48](https://user-images.githubusercontent.com/105324998/168129685-f2e0e316-508a-4025-9751-2a6608533892.png)

**Comment by 1551615** [comment]
3 days sync doesn't work between Yoroi wallet and ERGO blockchain.

**Comment by 1551615** [comment]
10 days sync doesn't work between Yoroi wallet and ERGO blockchain. Since no one from devs going to do anything, and I basically cannot do anything with ERG on current wallet: receive and send are blocked, I will keep updating this post as a warning for the people who plan to use Yoroi wallet -- DO NOT USE IT.

**Comment by 1551615** [comment]
Found a solution:
"...restore your seed phrase with nautilus wallet and never look back..."
