### ISSUE TITLE
Logo inconsistent color behavior

### ISSUE THREAD

**Issue by Mercurial** [Emurgo/yoroi-frontend#286]
Hi guys, Clark here!

Logo color seems to be having an inconsistent behavior, at initial load the color of the logo is the following:
![image](https://user-images.githubusercontent.com/585569/52398492-33259a80-2af4-11e9-8c9f-aace0886fe5a.png)

hover ever upon navigating to settings "just by clicking settings icon" the logo becomes another color

![image](https://user-images.githubusercontent.com/585569/52398509-459fd400-2af4-11e9-91f1-d81c97cabd22.png)

Really minor thing I noticed.

Thanks!
Clark

**Comment by vantuz-subhuman** [comment]
This is part of the design - icons change color to highlight the selected section ) 

![image](https://user-images.githubusercontent.com/5585355/52428794-c3270c80-2b13-11e9-98e2-7fc951cc2372.png)

![image](https://user-images.githubusercontent.com/5585355/52428816-cfab6500-2b13-11e9-9262-06c4a6d288ef.png)

![image](https://user-images.githubusercontent.com/5585355/52428842-dd60ea80-2b13-11e9-9a4f-bbcfbbd761ae.png)

![image](https://user-images.githubusercontent.com/5585355/52428870-ee116080-2b13-11e9-9634-11d63ec29586.png)

**Comment by SebastienGllmt** [comment]
Yeah maybe this isn't the best behavior from a UX point-of-view but it is expected.

**Comment by Mercurial** [comment]
sorry I thought it was a bug
