### ISSUE TITLE
Fix chevron misplacements on dropdowns

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-frontend#288]
Hi friends,

It is hard not to notice that the visual style of Yoroi browser wallet doesn't follow the style of the mobile app, the wallet website, or other marketing materials.

Additionally, there are issues with Yoroi extension UI components. These do not get in the way of wallet's functionality but leave a bad impression. Here is the screenshot of the very first screen that user sees after installing the extension:
![image](https://user-images.githubusercontent.com/5859177/52515679-82cda880-2c51-11e9-941e-4f5ac8367ca4.png)
As you can see, the chevron of the dropdown is misplaced, and the text on the button is not aligned properly. These problems are consistent across the app:
![image](https://user-images.githubusercontent.com/5859177/52515703-bf010900-2c51-11e9-94b2-94f3e3c4ed66.png)
![image](https://user-images.githubusercontent.com/5859177/52515706-c4f6ea00-2c51-11e9-832b-1c8d08a66b50.png)

Is anyone already working on refubrishing the UI? If not, I'd be happy to help and not only fix the small issues and make it pixel-perfect, but make the design of all UI components consistent with Yoroi mobile.

**Comment by SebastienGllmt** [comment]
Hey,
These are mostly historic issues and we definitely plan to redo the UI of the app. In fact, you can see the PR that started this process (#285 ) but our team is not so big so it's hard to find time for this in-between all the other stuff we have to do. Notably, #285 is on-pause right now (part of the reason it has so many merge conflicts 😔 )

If you want to help contribute you are definitely welcome to building on-top of the #285 branch!

**Comment by ebeloded** [comment]
Thanks, Sebastien! I'll take a look at #285, see where it stands. 

@NikeOnly Do you have any advice before I get into it?

**Comment by SebastienGllmt** [comment]
@ebeloded I hope you don't mind I renamed this issue to track the specific problem you mentioned.

**Comment by SebastienGllmt** [comment]
Closing since this has been fixed
