### ISSUE TITLE
Arrow icon needed on clickable transactions in the "Transactions" tab

### ISSUE THREAD

**Issue by Leo-Emurgo** [Emurgo/yoroi-frontend#309]
There is currently no indication to users that clicking a transaction will display details on that transaction, including the transaction ID. 

There should be an arrow icon or similar, indicating that the element is clickable and can be expanded.

**Comment by sarveshwar-singh** [comment]
Will be fixed In: https://github.com/Emurgo/yoroi-frontend/pull/285
