### ISSUE TITLE
Some corrections proposed for the fr-FR

### ISSUE THREAD

**Issue by psychomb** [Emurgo/yoroi-frontend#315]
Please find below some typos/grammatical errors corrections or potential improvements for the fr-FR messages. Some explanations when required.

Cheers,

[Yoroi_corrections.txt](https://github.com/Emurgo/yoroi-frontend/files/2898325/Yoroi_corrections.txt)

**Comment by SebastienGllmt** [comment]
Closing since these were all updated in Crowdin 👍
