### ISSUE TITLE
dispose TrezorConnect iframe when not in use

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#331]

**Comment by nicarq** [comment]
@sarveshwar-singh could you write more about this? I’m curious to know more like for example how affects Yoroi

**Comment by sarveshwar-singh** [comment]
@nicarq 
Trezor iframe keeps in memory even if it's not needed (in other words iframe is only needed when we need to communicate with Trezor device which is when we create wallet using Trezor and Sending Tx using Trezor).

Also similar issue is added by @ebeloded https://github.com/Emurgo/yoroi-frontend/issues/410, and closing  this issue because we have more details over here: https://github.com/Emurgo/yoroi-frontend/issues/410
