### ISSUE TITLE
Build-number in version for QA builds

### ISSUE THREAD

**Issue by vantuz-subhuman** [Emurgo/yoroi-frontend#355]
We need to add some unique build-number to version when build is created for our QA. They have problem navigating thru multiple builds from different branches, with the same version in all of them.

We prolly can create separate script for when you build something for QA and other internal use, even if it's "mainnet" build. When build is for internal use - it should append some additional identified for the build.

It would be extra cool if script could take branch name from the local git and append it to the version, and then also take the current commit hash and append last 4-5 chars to the end too.

**Comment by SebastienGllmt** [comment]
Closed by #625
