### ISSUE TITLE
Bug: cannot paste recovery phrase

### ISSUE THREAD

**Issue by sempruijs** [Emurgo/yoroi-frontend#3695]
This is a problem regarding the IOS version of yoroi.

Situation:
I want to import an existing wallet from my clipboard.
I've coppied my recovery phrase and tried to paste it in the first textfield.

The bug:
All the 24 words were pasted in the first textfield that was meant for the first word.

What I've expected to happen:
All the 24 should've been filled into the according textfields. the first word for the first textfield, the second word for the second textfield and so in.

Workaround:
Type in each word manually.

The words in the recovery phrase are sepperated with a single space like so:
```
hello world alice bob
```

**Comment by Nebyt** [comment]
Hi @sempruijs! It is the yoroi extension project.
Please, re-create your issue in the [correct project](https://github.com/Emurgo/yoroi).
But TBH, it doesn't sound like a bug, it sounds more like improvement.

**Comment by sempruijs** [comment]
Ahh thank you for the feedback @Nebyt! Created an issue over there :)
