### ISSUE TITLE
Logout from the yorio chrome wallet

### ISSUE THREAD

**Issue by dfter** [Emurgo/yoroi-frontend#374]
Is there a way to logout from the yoroi chrome wallet?

I did like to keep my balance confidentinal because now everbody can see the balance of my ada and the adresses linked to me. if somebody clicks on the yoroi extension.

Kind Regards

**Comment by SebastienGllmt** [comment]
If you go to Settings, you can select “Remove Wallet” which will remove whatever wallet you have selected at the moment.
