### ISSUE TITLE
Incorrect fee on incoming transactions

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-frontend#383]
It seems that for all incoming transactions the fee of the transaction is shown as 0.000000
![Yoroi](https://user-images.githubusercontent.com/5859177/55526325-d6db9300-56be-11e9-84ba-e154b59e7c0b.png)

Transactions always have a non-zero fee, so this is either a bug or a misleading way to show that someone else paid the transaction fee.

If we want to have a bank-like UI, where the recipient is not presented with the information about fees paid by the other party, then we should remove the Fee line (like we do in mobile).

On the other hand, receiving transactions is always free, and the information about fees is informative, so showing the value could be helpful.

**Background:**

Ledger has no problems with showing fees:

![Ledger](https://user-images.githubusercontent.com/5859177/55527461-5cf9d880-56c3-11e9-9262-cb9e940e4078.png)

Daedalus, on the other hand, doesn't show fees even on sent transactions:

![Daedalus](https://user-images.githubusercontent.com/5859177/55527544-ba8e2500-56c3-11e9-9219-43e0c472f62f.png)

AdaLite displays all fees:

![AdaLite](https://user-images.githubusercontent.com/5859177/55527623-15278100-56c4-11e9-9225-987d59abdfd5.png)

In my opinion, we should consider this a bug and show the actual fee.

**Comment by SebastienGllmt** [comment]
I would just remove the line from the UI. The API-level code for calculating the fees is shared between this repository and the mobile codebase so it would be detrimental to change it.
