### ISSUE TITLE
Move "Create a new wallet" to the top of the ADD WALLET menu

### ISSUE THREAD

**Issue by Leo-Emurgo** [Emurgo/yoroi-frontend#388]
![Screenshot_1](https://user-images.githubusercontent.com/44602017/55700712-5218ae00-5a0b-11e9-99c4-de70a5066758.png)

I think new users should see the "Create a new wallet" option first at the top of this list.

**Comment by SebastienGllmt** [comment]
I'm going to close this issue since we're going to be redesigning this screen soon anyway.
