### ISSUE TITLE
Greenkeeping

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-frontend#393]
Following the issue about upgrading React #392, I would like to propose a much more difficult endeavor, which is to upgrade all dependencies we can upgrade and integrate [Greenkeeper](https://greenkeeper.io/) to automate the process of keeping things always up to date.

**Why do it?**
Upgrading dependencies is a chore, which no one does, unless it adds some functional value, or fixes some bugs. Should there be a fix or marginal improvement in the dependency tree (which happens continuously), it is usually ignored. The result of this is that the dependency tree becomes stale and hard to update. If at some point we decide that we would like to use a new feature (say, React hooks), which would require an update to one of the core dependencies, the result of this is a rabbit hole without exit, a chain of problems impossible to resolve. At some point, you may find yourself realizing that the project is stuck, and there is no way to upgrade without a major overhaul.

Greenkeeper would help us by keeping an eye on all our dependencies and creating a PR if there is an upgrade. The CI will run all the checks and we will be able to decide, whether to include the upgrade or not. And of course, if we want to fix versions of some dependencies, we can easily do that.

In the end, keeping things green will end up being a simple automated process, which would benefit us in the long run. 

**Can we do it?**
First, setting up greenkeeper depends on having reliable test coverage to make sure that CI checks fail when they have to.
Second, we will need to go over our dependencies and upgrade everything we can and fix what we can't. The difficulty of this is extremely hard to estimate.

A nice thing is that Greenkeeper is totally free for open source projects

What do you guys think?

**Comment by SebastienGllmt** [comment]
In my experience, tools like Greenkeeping cause a huge amount of noise in your Github and for most dependencies upgrades you actually care about require your help to make the upgrade anyway.
I wouldn't implement something like this until we get better testing and release candidates going for Yoroi which won't happen until at least after Icarus v2 since for sure we will accidentally break one thing otherwise. Afterwards I don't mind trying it out if you want to spend the time on it.

**Comment by SebastienGllmt** [comment]
Now that Depndabot is acquired by Github and already does security PRs automatically by default plus now we have screenshot testing enabled, it makes sense to try this out. I enabled it for our repo and hopefully it won't be too spammy
