### ISSUE TITLE
Suggestion: Implement a UI element to collapse/expand ADA balance display

### ISSUE THREAD

**Issue by Leo-Emurgo** [Emurgo/yoroi-frontend#409]
Many users are uncomfortable with their ADA balance immediately showing when Yoroi is opened (this is true for both the PC and mobile versions). 

I think the ability to hide balance by default, and click a chevron/arrow icon to expand or collapse the balance would be a welcome addition. 

Very bad mockup images of how this might work: 

https://imgur.com/a/2R3mdZZ

**Comment by ebeloded** [comment]
A good example of this can be found in crypto.com app:

![IMG_2B60F74845B4-1](https://user-images.githubusercontent.com/5859177/56478046-32d35380-64d6-11e9-8e21-a66e98710666.jpeg)

I think the UI and UX for this feature should be done in the same way. The 👁icon is often used to show/hide sensitive values. @Marta-Ryzhok, could you think of a nice way to add this to our designs?

PS. Here is the same feature request for mobile: https://github.com/Emurgo/yoroi-mobile/issues/651#issue-423242441

**Comment by SebastienGllmt** [comment]
Fixed by https://github.com/Emurgo/yoroi-frontend/pull/710
