### ISSUE TITLE
Trezor iframe and assets are loaded without being needed

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-frontend#410]
The iframe necessary to connect to Trezor is injected, and accompanying 1.4MB of JavaScript (480KB gzipped) are loaded, parsed and executed.

Expected behavior:
Load trezor resources only if user needs them (when connecting to Trezor, or if Trezor wallet is configured).

**Comment by SebastienGllmt** [comment]
Yes we did this for Ledger but not for Trezor so maybe a similar system can be reused.

Additionally (but also with really low priority) we shouldn't ask for user permission to use Trezor Connect when you install the app but instead only ask it when you actually try to create a wallet with Trezor.

**Comment by sarveshwar-singh** [comment]
Similar to: https://github.com/Emurgo/yoroi-frontend/issues/331

**Comment by SebastienGllmt** [comment]
We fixed this a while ago so I'm closing the issue.
