### ISSUE TITLE
add password usages declaration

### ISSUE THREAD

**Issue by shinsuny** [Emurgo/yoroi-frontend#45]
While setting password user does not know why he is setting password and when he will use it, how about adding a note that this password will be used when sending ADA. 
( so user might set a better and secure password )

![image 1](https://user-images.githubusercontent.com/19986226/47141727-4968da00-d2fc-11e8-9c67-921b069d4ace.png)

**Comment by coreyar** [comment]
Is this issue still relevant? The input label and placeholder now reads "Spending password" which is clearer than the previous label.

**Comment by shinsuny** [comment]
@coreyar 
Yes, its cleaner now.
Good to close.
