### ISSUE TITLE
improve user friendliness while [ Create a new wallet ] OR [ Restore wallet from backup ]

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#46]
While [ Create a new wallet ] OR [ Restore wallet from backup ] if user presses ESC key or clicks somewhere apart from dialog box anytime then,
Dialog box is closed and user have to repeat whole process even if he has written  RECOVERY PHRASE and about to complete the wallet creation.

One Solution:
we should only close dialog box if user presses "X" button.

![image 2](https://user-images.githubusercontent.com/19986226/47141973-d2801100-d2fc-11e8-97b8-53add66cd76a.png)

**Comment by SebastienGllmt** [comment]
We already do this for a lot of Dialog boxes. The Dialog class actually has a property for this if I remember correctly so it should be really simple.

**Comment by sarveshwar-singh** [comment]
@sarveshwar-singh 
Yes, just have to set `closeOnOverlayClick={false}`.
Thinking to fix that in: https://github.com/Emurgo/yoroi-frontend/pull/285

**Comment by Leo-Emurgo** [comment]
Still not fixed, also "MOUSE UP" will close the window. Not just clicking. 

In my own testing I accidentally close the window multiple times almost every time I try to restore a wallet due to this bug.
