### ISSUE TITLE
Firefox (v67.0.4) not showing balances or tranaction history after restore for Yoroi 1.8.1

### ISSUE THREAD

**Issue by Thorny-Twig** [Emurgo/yoroi-frontend#793]
Hello Emurgo support team, I was told on TG Cardano Community Tech Support channel to report bug / issue in here. 

Newly released Yoroi 1.8.1 Firefox V67.0.4 extension isn't loading balance or transaction history after restore process. If you go into the receive transaction tab the page seems to be stuck trying to load up something.

In fact I also noticed it doesn't show the "Cardano Payment URL's" UI/UX page. Don't know if anyone can replicate. It worked on Chrome on a Ubuntu 19.04 machine so?

I can post logs if required. Note: I cleared FF cache and tried reinstalled without adblockers also to see if they effected the process, a couple of times but no luck, same issue all the time.

**Comment by Thorny-Twig** [comment]
So it turns out that it's something to do with my Firefox settings. I had under "Preferences" -> "Privacy & Security" -> "History" -> "Never Remember History" is enabled. So it seems that this setting is required,  my bad. Would there need to be a educate/inform and provide a pop up UI/UX message to savvy privacy Firefox users that do not tend to hold on to their browsing history that this is currently a required setting for Yoroi wallet to work correctly with intended behavior. Is there any future plans for a work around with above dilemma?

**Comment by SebastienGllmt** [comment]
This is a known bug and it's because of the storage API we use. To save to localstorage we use `window.localStorage` (which works just fine for Chrome) but Firefox wants you to instead use `storage.local`. The behavior of `window.localStorage` on Firefox is affected by your privacy settings, browser history, etc. and so it doesn't work well for some users.

**Comment by rdlrt** [comment]
Just to add the error message and version details , in case someone else faces this meanwhile:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0
Engine: Gecko 67.0
arch: amd64
OS: Ubuntu
Error: 
LoadingStore::setup Unable to load libraries {
  "code": 361,
  "message": "http://google.github.io/lovefield/error_lookup/src/error_lookup.html?c=361&p0=InvalidStateError&p1=A%20mutation%20operation%20was%20attempted%20on%20a%20database%20that%20did%20not%20al"
}

Which (URL) converts to.. "Unable to open _IndexedDB database_: InvalidStateError, A mutation operation was attempted on a database that did not al."

**Comment by SebastienGllmt** [comment]
Should be fixed once Yoroi 1.9 ships. fixed by #816
