### ISSUE TITLE
app/api/ada/_createWalletFromServerData name is irrelevant to Yoroi

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#83]
`app/api/ada/_createWalletFromServerData`
we should give it a better name.
it only coverts wallet data fetched from localStore to new `Wallet` object, there is no server involved.

**Comment by SebastienGllmt** [comment]
yeah maybe something like `mapWalletToCommonApi`

**Comment by SebastienGllmt** [comment]
These are gone in storagev2 so I'm closing this
