### ISSUE TITLE
How to broadcast transaction following Daedalus transfer example?

### ISSUE THREAD

**Issue by mmo2112** [Emurgo/yoroi-frontend#879]
I've done with this example (daedalusTransfer.test.js), and have a json like that:
{"tx":{"inputs":[{"id":"000","index":0}],"outputs":[{"address":"AAA","value":99834159}]},"witness":[{"PkWitness":["123","456"]}]}
I have searched some few methods but not any useful, please help me to continue, thanks so much.

**Comment by SebastienGllmt** [comment]
Look at `app/api/ada/daedalusTransfer.js`

To send a transaction you need access to a fullnode that will broadcast your transaction.

**Comment by SebastienGllmt** [comment]
Note that we don't have any nice utility functions for sending Daedalus transactions in the Yoroi codebase because Yoroi doesn't support Daedalus wallets. Hopefully the above example is enough so that you understand the approach.

**Comment by mmo2112** [comment]
> Note that we don't have any nice utility functions for sending Daedalus transactions in the Yoroi codebase because Yoroi doesn't support Daedalus wallets.
I want to use function Transfer all funds from Daedalus like Yoroi front-end. I have read both your example and daedalusTransfer.js, switch to NodeJS to test. After txFinalizer.finalize(), the result is entropy/json format. I also have a full Cardano node, like other crypto (ex bitcoin, ethereum,...), it must have serialize method then broadcasting it on node, but I can't find anyway to serialize the result, same to broadcast on node (Cardano API doc doesn't have). Another repository on Git is adalite-go but seems not like your example. Thanks so much for your hard support.

**Comment by SebastienGllmt** [comment]
https://github.com/Emurgo/yoroi-frontend/blob/develop/app/api/ada/lib/state-fetch/remoteFetcher.js#L132
This is the function that takes a `Wallet.SignedTransaction` and sends it to our backend (which is based off https://github.com/input-output-hk/project-icarus-backend-service/blob/77cb385aae81b60f2df13c93c582a836433a051e/src/routes.js#L126 )

**Comment by mmo2112** [comment]
Again, thank you so much bro, I have done on broadcasting, issue is closed.
