### ISSUE TITLE
About address derivation path and signing.

### ISSUE THREAD

**Issue by mmo2112** [Emurgo/yoroi-frontend#883]
Hi there, I have worked with Bitcoin and Ehereum, which are using hdkey lib to derive main account to multiple address with path. In these crypto, derivation path is declared by string, example: "/0/0/1" or "/0/0/1/0",...
But in wasm library, it uses a number between 0x80000000 and 0xFFFFFFFF, or I've read not carefully. Example I have a root privateKey, I can dirive it by specific path to sign with corresponding address.
So I have few questions, how to know which path I'm using, example in Yoroi is: `m/44'/1815'/0'/0/1`?
My test case is:
Create account from Yoroi with memos and spending password, then create in wasm with same information.
```
const cardano = require('cardano-wallet');
const MEMO = "...";
const SPENDING_PASSWORD = "...";
const entropy = cardano.Entropy.from_english_mnemonics(MEMO);
let wallet = cardano.Bip44RootPrivateKey.recover(entropy, SPENDING_PASSWORD);
const privateKey = wallet.key().to_hex();
console.log("privateKey", privateKey);
```
Is it a root privateKey? Then, I create an address:
```
let account = wallet.bip44_account(cardano.AccountIndex.new(0x80000000));
let account_public = account.public();
   
// create an address
let chain_pub = account_public.bip44_chain(false);
let key_pub = chain_pub.address_key(cardano.AddressKeyIndex.new(0));
let address = key_pub.bootstrap_era_address(cardano.BlockchainSettings.mainnet());
console.log("Address", address.to_base58());
```
So I have address index = 0 (using to get address key from root key), chainpub = false, then I transfer few Ada to this address and trying to sign via wasm but I've got stuck in signing, invalid witness. Is my test case valid or not? 
And the last problem is this address, which created by this way is not same on my Yoroi account including same memos and spending password, I don't know why. Thanks for reading and supporting so much.

**Comment by nicarq** [comment]
I don’t know what library you are using for Ethereum or Bitcoin, but [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) talks about what it means 0x80000000 which is related to the `'` that you see next to the numbers.

For specific help related to the WASM library, I would go to the wasm library repository though.

**Comment by nicarq** [comment]
I’m going to close this issue because this repo is about Yoroi and not about the WASM library.

**Comment by mmo2112** [comment]
@nicarq,
Im using it, both supported for btc/eth:
https://www.npmjs.com/package/hdkey

**Comment by mmo2112** [comment]
@nicarq, may you help me to get address string path like Yoroi, thanks so much.
