### ISSUE TITLE
Quick links feature

### ISSUE THREAD

**Issue by hellc** [Emurgo/yoroi-frontend#99]
Provide an ability to _initiate sending funds_ apps dialogs based on "quick links" with universal URL Scheme.

It will allows to open compatible applications on "send screen" with preinstalled data like receiver **address**, **amount** of funds to send and **token symbol** (for the future multi-currency cardano blockchain support) _from QR Codes, online shops and etc_.

Example:

`http://kxp.one/cardano.html?address="< some address >"&amount="100"&token="ADA"`
or `https://send.cardano.org?address="< some address >"&amount="100"&token="ADA"`
or whatever you decide...

For URLScheme this link will looks like 
`cardano://send?address="< some address >"&amount="100"&token="ADA"`

**Web page logic:**
Internal page script should check available apps that could open URLScheme (for iOS and Android apps) or to call chrome extension method. Then redirect inside the available one with focus on sending funds context with preinstalled context info. 

For Yoroi chrome extension:
Try to call custom js function:
```
function cardanoSendFunction() {
    chrome.runtime.sendMessage('ffnbelfdoeiohenkjibnmadjiehjhajb', {
      message: "cardano://send?address="< some address >"&amount="100"&token="ADA"" 
    });
}
```
where: "ffnbelfdoeiohenkjibnmadjiehjhajb" - Yoroi chrome store extension ID.

If it fails, then - you don't have supported chrome extension.
Next try to call URL Scheme link. If it fails too -> present verified apps download page.

### Yoroi chrome extension integration guide:
(already tested - should works safely)

1. Provide _externally_connectable_ manifest info:
```
"background": {
    "page": "background.html"
  },
...
  "externally_connectable": {
    "matches": ["*://*.kxp.one/*"]
  },
...
  "permissions": [
    "tabs",
    "storage"
  ],
```
2. Add _background.js_ external messages listened
`chrome.runtime.onMessageExternal.addListener(< some function >);`
Function description:
If it starts with "cardano://send"... - check message info and open Yoroi chrome tab with send funds dialog; Preinstall data from message url params.

### Upcoming iOS and Android apps (Yoroi? =)) integration guide:

Please visit official vendors pages for more info. It must be easy to implement. I did it many times.

Apple URL Scheme Guide:
https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app?language=objc

Android Guide:
https://developer.android.com/training/app-links/deep-linking

### Less efforts to implement but we could get so much profit of it...

**Comment by SebastienGllmt** [comment]
Hey. I actually wrote a small spec for this feature [here](https://docs.google.com/document/d/1hssGQzQdd9CaHHKrFyLAY9yyPewD06dtqiwwrSQhUUU/edit?usp=sharing)

**Comment by hellc** [comment]
@SebastienGllmt I haven't tested "web+" protocol handler yet. Looks good. Seems like background listener is more flexible and "alerts free".

And you could you use more ways to initiate transaction from "router like" verified page. You could control it, so - more security. I don't know. We need to examine the best way to do it.

**Comment by SebastienGllmt** [comment]
Closing since we started working on the URI Scheme spec
